package io.mtc.modules.sap.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BplidPeriodExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table @MTC_OFPR1
     *
     * @mbg.generated Wed Mar 06 15:55:22 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table @MTC_OFPR1
     *
     * @mbg.generated Wed Mar 06 15:55:22 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table @MTC_OFPR1
     *
     * @mbg.generated Wed Mar 06 15:55:22 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     *
     */
    public BplidPeriodExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *
     * @param orderByClause
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *
     * @param distinct
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     *
     * @param criteria
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     *
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table @MTC_OFPR1
     *
     * @mbg.generated Wed Mar 06 15:55:22 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCodeIsNull() {
            addCriterion("\"Code\" is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("\"Code\" is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("\"Code\" =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("\"Code\" <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("\"Code\" >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("\"Code\" >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("\"Code\" <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("\"Code\" <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("\"Code\" like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("\"Code\" not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("\"Code\" in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("\"Code\" not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("\"Code\" between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("\"Code\" not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andLineidIsNull() {
            addCriterion("\"LineId\" is null");
            return (Criteria) this;
        }

        public Criteria andLineidIsNotNull() {
            addCriterion("\"LineId\" is not null");
            return (Criteria) this;
        }

        public Criteria andLineidEqualTo(Integer value) {
            addCriterion("\"LineId\" =", value, "lineid");
            return (Criteria) this;
        }

        public Criteria andLineidNotEqualTo(Integer value) {
            addCriterion("\"LineId\" <>", value, "lineid");
            return (Criteria) this;
        }

        public Criteria andLineidGreaterThan(Integer value) {
            addCriterion("\"LineId\" >", value, "lineid");
            return (Criteria) this;
        }

        public Criteria andLineidGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"LineId\" >=", value, "lineid");
            return (Criteria) this;
        }

        public Criteria andLineidLessThan(Integer value) {
            addCriterion("\"LineId\" <", value, "lineid");
            return (Criteria) this;
        }

        public Criteria andLineidLessThanOrEqualTo(Integer value) {
            addCriterion("\"LineId\" <=", value, "lineid");
            return (Criteria) this;
        }

        public Criteria andLineidIn(List<Integer> values) {
            addCriterion("\"LineId\" in", values, "lineid");
            return (Criteria) this;
        }

        public Criteria andLineidNotIn(List<Integer> values) {
            addCriterion("\"LineId\" not in", values, "lineid");
            return (Criteria) this;
        }

        public Criteria andLineidBetween(Integer value1, Integer value2) {
            addCriterion("\"LineId\" between", value1, value2, "lineid");
            return (Criteria) this;
        }

        public Criteria andLineidNotBetween(Integer value1, Integer value2) {
            addCriterion("\"LineId\" not between", value1, value2, "lineid");
            return (Criteria) this;
        }

        public Criteria andObjectIsNull() {
            addCriterion("\"Object\" is null");
            return (Criteria) this;
        }

        public Criteria andObjectIsNotNull() {
            addCriterion("\"Object\" is not null");
            return (Criteria) this;
        }

        public Criteria andObjectEqualTo(String value) {
            addCriterion("\"Object\" =", value, "object");
            return (Criteria) this;
        }

        public Criteria andObjectNotEqualTo(String value) {
            addCriterion("\"Object\" <>", value, "object");
            return (Criteria) this;
        }

        public Criteria andObjectGreaterThan(String value) {
            addCriterion("\"Object\" >", value, "object");
            return (Criteria) this;
        }

        public Criteria andObjectGreaterThanOrEqualTo(String value) {
            addCriterion("\"Object\" >=", value, "object");
            return (Criteria) this;
        }

        public Criteria andObjectLessThan(String value) {
            addCriterion("\"Object\" <", value, "object");
            return (Criteria) this;
        }

        public Criteria andObjectLessThanOrEqualTo(String value) {
            addCriterion("\"Object\" <=", value, "object");
            return (Criteria) this;
        }

        public Criteria andObjectLike(String value) {
            addCriterion("\"Object\" like", value, "object");
            return (Criteria) this;
        }

        public Criteria andObjectNotLike(String value) {
            addCriterion("\"Object\" not like", value, "object");
            return (Criteria) this;
        }

        public Criteria andObjectIn(List<String> values) {
            addCriterion("\"Object\" in", values, "object");
            return (Criteria) this;
        }

        public Criteria andObjectNotIn(List<String> values) {
            addCriterion("\"Object\" not in", values, "object");
            return (Criteria) this;
        }

        public Criteria andObjectBetween(String value1, String value2) {
            addCriterion("\"Object\" between", value1, value2, "object");
            return (Criteria) this;
        }

        public Criteria andObjectNotBetween(String value1, String value2) {
            addCriterion("\"Object\" not between", value1, value2, "object");
            return (Criteria) this;
        }

        public Criteria andLoginstIsNull() {
            addCriterion("\"LogInst\" is null");
            return (Criteria) this;
        }

        public Criteria andLoginstIsNotNull() {
            addCriterion("\"LogInst\" is not null");
            return (Criteria) this;
        }

        public Criteria andLoginstEqualTo(Integer value) {
            addCriterion("\"LogInst\" =", value, "loginst");
            return (Criteria) this;
        }

        public Criteria andLoginstNotEqualTo(Integer value) {
            addCriterion("\"LogInst\" <>", value, "loginst");
            return (Criteria) this;
        }

        public Criteria andLoginstGreaterThan(Integer value) {
            addCriterion("\"LogInst\" >", value, "loginst");
            return (Criteria) this;
        }

        public Criteria andLoginstGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"LogInst\" >=", value, "loginst");
            return (Criteria) this;
        }

        public Criteria andLoginstLessThan(Integer value) {
            addCriterion("\"LogInst\" <", value, "loginst");
            return (Criteria) this;
        }

        public Criteria andLoginstLessThanOrEqualTo(Integer value) {
            addCriterion("\"LogInst\" <=", value, "loginst");
            return (Criteria) this;
        }

        public Criteria andLoginstIn(List<Integer> values) {
            addCriterion("\"LogInst\" in", values, "loginst");
            return (Criteria) this;
        }

        public Criteria andLoginstNotIn(List<Integer> values) {
            addCriterion("\"LogInst\" not in", values, "loginst");
            return (Criteria) this;
        }

        public Criteria andLoginstBetween(Integer value1, Integer value2) {
            addCriterion("\"LogInst\" between", value1, value2, "loginst");
            return (Criteria) this;
        }

        public Criteria andLoginstNotBetween(Integer value1, Integer value2) {
            addCriterion("\"LogInst\" not between", value1, value2, "loginst");
            return (Criteria) this;
        }

        public Criteria andUYearcodeIsNull() {
            addCriterion("\"U_YearCode\" is null");
            return (Criteria) this;
        }

        public Criteria andUYearcodeIsNotNull() {
            addCriterion("\"U_YearCode\" is not null");
            return (Criteria) this;
        }

        public Criteria andUYearcodeEqualTo(String value) {
            addCriterion("\"U_YearCode\" =", value, "uYearcode");
            return (Criteria) this;
        }

        public Criteria andUYearcodeNotEqualTo(String value) {
            addCriterion("\"U_YearCode\" <>", value, "uYearcode");
            return (Criteria) this;
        }

        public Criteria andUYearcodeGreaterThan(String value) {
            addCriterion("\"U_YearCode\" >", value, "uYearcode");
            return (Criteria) this;
        }

        public Criteria andUYearcodeGreaterThanOrEqualTo(String value) {
            addCriterion("\"U_YearCode\" >=", value, "uYearcode");
            return (Criteria) this;
        }

        public Criteria andUYearcodeLessThan(String value) {
            addCriterion("\"U_YearCode\" <", value, "uYearcode");
            return (Criteria) this;
        }

        public Criteria andUYearcodeLessThanOrEqualTo(String value) {
            addCriterion("\"U_YearCode\" <=", value, "uYearcode");
            return (Criteria) this;
        }

        public Criteria andUYearcodeLike(String value) {
            addCriterion("\"U_YearCode\" like", value, "uYearcode");
            return (Criteria) this;
        }

        public Criteria andUYearcodeNotLike(String value) {
            addCriterion("\"U_YearCode\" not like", value, "uYearcode");
            return (Criteria) this;
        }

        public Criteria andUYearcodeIn(List<String> values) {
            addCriterion("\"U_YearCode\" in", values, "uYearcode");
            return (Criteria) this;
        }

        public Criteria andUYearcodeNotIn(List<String> values) {
            addCriterion("\"U_YearCode\" not in", values, "uYearcode");
            return (Criteria) this;
        }

        public Criteria andUYearcodeBetween(String value1, String value2) {
            addCriterion("\"U_YearCode\" between", value1, value2, "uYearcode");
            return (Criteria) this;
        }

        public Criteria andUYearcodeNotBetween(String value1, String value2) {
            addCriterion("\"U_YearCode\" not between", value1, value2, "uYearcode");
            return (Criteria) this;
        }

        public Criteria andUFccodeIsNull() {
            addCriterion("\"U_FcCode\" is null");
            return (Criteria) this;
        }

        public Criteria andUFccodeIsNotNull() {
            addCriterion("\"U_FcCode\" is not null");
            return (Criteria) this;
        }

        public Criteria andUFccodeEqualTo(String value) {
            addCriterion("\"U_FcCode\" =", value, "uFccode");
            return (Criteria) this;
        }

        public Criteria andUFccodeNotEqualTo(String value) {
            addCriterion("\"U_FcCode\" <>", value, "uFccode");
            return (Criteria) this;
        }

        public Criteria andUFccodeGreaterThan(String value) {
            addCriterion("\"U_FcCode\" >", value, "uFccode");
            return (Criteria) this;
        }

        public Criteria andUFccodeGreaterThanOrEqualTo(String value) {
            addCriterion("\"U_FcCode\" >=", value, "uFccode");
            return (Criteria) this;
        }

        public Criteria andUFccodeLessThan(String value) {
            addCriterion("\"U_FcCode\" <", value, "uFccode");
            return (Criteria) this;
        }

        public Criteria andUFccodeLessThanOrEqualTo(String value) {
            addCriterion("\"U_FcCode\" <=", value, "uFccode");
            return (Criteria) this;
        }

        public Criteria andUFccodeLike(String value) {
            addCriterion("\"U_FcCode\" like", value, "uFccode");
            return (Criteria) this;
        }

        public Criteria andUFccodeNotLike(String value) {
            addCriterion("\"U_FcCode\" not like", value, "uFccode");
            return (Criteria) this;
        }

        public Criteria andUFccodeIn(List<String> values) {
            addCriterion("\"U_FcCode\" in", values, "uFccode");
            return (Criteria) this;
        }

        public Criteria andUFccodeNotIn(List<String> values) {
            addCriterion("\"U_FcCode\" not in", values, "uFccode");
            return (Criteria) this;
        }

        public Criteria andUFccodeBetween(String value1, String value2) {
            addCriterion("\"U_FcCode\" between", value1, value2, "uFccode");
            return (Criteria) this;
        }

        public Criteria andUFccodeNotBetween(String value1, String value2) {
            addCriterion("\"U_FcCode\" not between", value1, value2, "uFccode");
            return (Criteria) this;
        }

        public Criteria andUStdateIsNull() {
            addCriterion("\"U_StDate\" is null");
            return (Criteria) this;
        }

        public Criteria andUStdateIsNotNull() {
            addCriterion("\"U_StDate\" is not null");
            return (Criteria) this;
        }

        public Criteria andUStdateEqualTo(Date value) {
            addCriterion("\"U_StDate\" =", value, "uStdate");
            return (Criteria) this;
        }

        public Criteria andUStdateNotEqualTo(Date value) {
            addCriterion("\"U_StDate\" <>", value, "uStdate");
            return (Criteria) this;
        }

        public Criteria andUStdateGreaterThan(Date value) {
            addCriterion("\"U_StDate\" >", value, "uStdate");
            return (Criteria) this;
        }

        public Criteria andUStdateGreaterThanOrEqualTo(Date value) {
            addCriterion("\"U_StDate\" >=", value, "uStdate");
            return (Criteria) this;
        }

        public Criteria andUStdateLessThan(Date value) {
            addCriterion("\"U_StDate\" <", value, "uStdate");
            return (Criteria) this;
        }

        public Criteria andUStdateLessThanOrEqualTo(Date value) {
            addCriterion("\"U_StDate\" <=", value, "uStdate");
            return (Criteria) this;
        }

        public Criteria andUStdateIn(List<Date> values) {
            addCriterion("\"U_StDate\" in", values, "uStdate");
            return (Criteria) this;
        }

        public Criteria andUStdateNotIn(List<Date> values) {
            addCriterion("\"U_StDate\" not in", values, "uStdate");
            return (Criteria) this;
        }

        public Criteria andUStdateBetween(Date value1, Date value2) {
            addCriterion("\"U_StDate\" between", value1, value2, "uStdate");
            return (Criteria) this;
        }

        public Criteria andUStdateNotBetween(Date value1, Date value2) {
            addCriterion("\"U_StDate\" not between", value1, value2, "uStdate");
            return (Criteria) this;
        }

        public Criteria andUEnddateIsNull() {
            addCriterion("\"U_EndDate\" is null");
            return (Criteria) this;
        }

        public Criteria andUEnddateIsNotNull() {
            addCriterion("\"U_EndDate\" is not null");
            return (Criteria) this;
        }

        public Criteria andUEnddateEqualTo(Date value) {
            addCriterion("\"U_EndDate\" =", value, "uEnddate");
            return (Criteria) this;
        }

        public Criteria andUEnddateNotEqualTo(Date value) {
            addCriterion("\"U_EndDate\" <>", value, "uEnddate");
            return (Criteria) this;
        }

        public Criteria andUEnddateGreaterThan(Date value) {
            addCriterion("\"U_EndDate\" >", value, "uEnddate");
            return (Criteria) this;
        }

        public Criteria andUEnddateGreaterThanOrEqualTo(Date value) {
            addCriterion("\"U_EndDate\" >=", value, "uEnddate");
            return (Criteria) this;
        }

        public Criteria andUEnddateLessThan(Date value) {
            addCriterion("\"U_EndDate\" <", value, "uEnddate");
            return (Criteria) this;
        }

        public Criteria andUEnddateLessThanOrEqualTo(Date value) {
            addCriterion("\"U_EndDate\" <=", value, "uEnddate");
            return (Criteria) this;
        }

        public Criteria andUEnddateIn(List<Date> values) {
            addCriterion("\"U_EndDate\" in", values, "uEnddate");
            return (Criteria) this;
        }

        public Criteria andUEnddateNotIn(List<Date> values) {
            addCriterion("\"U_EndDate\" not in", values, "uEnddate");
            return (Criteria) this;
        }

        public Criteria andUEnddateBetween(Date value1, Date value2) {
            addCriterion("\"U_EndDate\" between", value1, value2, "uEnddate");
            return (Criteria) this;
        }

        public Criteria andUEnddateNotBetween(Date value1, Date value2) {
            addCriterion("\"U_EndDate\" not between", value1, value2, "uEnddate");
            return (Criteria) this;
        }

        public Criteria andUFstatusIsNull() {
            addCriterion("\"U_FStatus\" is null");
            return (Criteria) this;
        }

        public Criteria andUFstatusIsNotNull() {
            addCriterion("\"U_FStatus\" is not null");
            return (Criteria) this;
        }

        public Criteria andUFstatusEqualTo(String value) {
            addCriterion("\"U_FStatus\" =", value, "uFstatus");
            return (Criteria) this;
        }

        public Criteria andUFstatusNotEqualTo(String value) {
            addCriterion("\"U_FStatus\" <>", value, "uFstatus");
            return (Criteria) this;
        }

        public Criteria andUFstatusGreaterThan(String value) {
            addCriterion("\"U_FStatus\" >", value, "uFstatus");
            return (Criteria) this;
        }

        public Criteria andUFstatusGreaterThanOrEqualTo(String value) {
            addCriterion("\"U_FStatus\" >=", value, "uFstatus");
            return (Criteria) this;
        }

        public Criteria andUFstatusLessThan(String value) {
            addCriterion("\"U_FStatus\" <", value, "uFstatus");
            return (Criteria) this;
        }

        public Criteria andUFstatusLessThanOrEqualTo(String value) {
            addCriterion("\"U_FStatus\" <=", value, "uFstatus");
            return (Criteria) this;
        }

        public Criteria andUFstatusLike(String value) {
            addCriterion("\"U_FStatus\" like", value, "uFstatus");
            return (Criteria) this;
        }

        public Criteria andUFstatusNotLike(String value) {
            addCriterion("\"U_FStatus\" not like", value, "uFstatus");
            return (Criteria) this;
        }

        public Criteria andUFstatusIn(List<String> values) {
            addCriterion("\"U_FStatus\" in", values, "uFstatus");
            return (Criteria) this;
        }

        public Criteria andUFstatusNotIn(List<String> values) {
            addCriterion("\"U_FStatus\" not in", values, "uFstatus");
            return (Criteria) this;
        }

        public Criteria andUFstatusBetween(String value1, String value2) {
            addCriterion("\"U_FStatus\" between", value1, value2, "uFstatus");
            return (Criteria) this;
        }

        public Criteria andUFstatusNotBetween(String value1, String value2) {
            addCriterion("\"U_FStatus\" not between", value1, value2, "uFstatus");
            return (Criteria) this;
        }

        public Criteria andUChdateIsNull() {
            addCriterion("\"U_ChDate\" is null");
            return (Criteria) this;
        }

        public Criteria andUChdateIsNotNull() {
            addCriterion("\"U_ChDate\" is not null");
            return (Criteria) this;
        }

        public Criteria andUChdateEqualTo(Date value) {
            addCriterion("\"U_ChDate\" =", value, "uChdate");
            return (Criteria) this;
        }

        public Criteria andUChdateNotEqualTo(Date value) {
            addCriterion("\"U_ChDate\" <>", value, "uChdate");
            return (Criteria) this;
        }

        public Criteria andUChdateGreaterThan(Date value) {
            addCriterion("\"U_ChDate\" >", value, "uChdate");
            return (Criteria) this;
        }

        public Criteria andUChdateGreaterThanOrEqualTo(Date value) {
            addCriterion("\"U_ChDate\" >=", value, "uChdate");
            return (Criteria) this;
        }

        public Criteria andUChdateLessThan(Date value) {
            addCriterion("\"U_ChDate\" <", value, "uChdate");
            return (Criteria) this;
        }

        public Criteria andUChdateLessThanOrEqualTo(Date value) {
            addCriterion("\"U_ChDate\" <=", value, "uChdate");
            return (Criteria) this;
        }

        public Criteria andUChdateIn(List<Date> values) {
            addCriterion("\"U_ChDate\" in", values, "uChdate");
            return (Criteria) this;
        }

        public Criteria andUChdateNotIn(List<Date> values) {
            addCriterion("\"U_ChDate\" not in", values, "uChdate");
            return (Criteria) this;
        }

        public Criteria andUChdateBetween(Date value1, Date value2) {
            addCriterion("\"U_ChDate\" between", value1, value2, "uChdate");
            return (Criteria) this;
        }

        public Criteria andUChdateNotBetween(Date value1, Date value2) {
            addCriterion("\"U_ChDate\" not between", value1, value2, "uChdate");
            return (Criteria) this;
        }

        public Criteria andUIntrateIsNull() {
            addCriterion("\"U_IntRate\" is null");
            return (Criteria) this;
        }

        public Criteria andUIntrateIsNotNull() {
            addCriterion("\"U_IntRate\" is not null");
            return (Criteria) this;
        }

        public Criteria andUIntrateEqualTo(BigDecimal value) {
            addCriterion("\"U_IntRate\" =", value, "uIntrate");
            return (Criteria) this;
        }

        public Criteria andUIntrateNotEqualTo(BigDecimal value) {
            addCriterion("\"U_IntRate\" <>", value, "uIntrate");
            return (Criteria) this;
        }

        public Criteria andUIntrateGreaterThan(BigDecimal value) {
            addCriterion("\"U_IntRate\" >", value, "uIntrate");
            return (Criteria) this;
        }

        public Criteria andUIntrateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("\"U_IntRate\" >=", value, "uIntrate");
            return (Criteria) this;
        }

        public Criteria andUIntrateLessThan(BigDecimal value) {
            addCriterion("\"U_IntRate\" <", value, "uIntrate");
            return (Criteria) this;
        }

        public Criteria andUIntrateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("\"U_IntRate\" <=", value, "uIntrate");
            return (Criteria) this;
        }

        public Criteria andUIntrateIn(List<BigDecimal> values) {
            addCriterion("\"U_IntRate\" in", values, "uIntrate");
            return (Criteria) this;
        }

        public Criteria andUIntrateNotIn(List<BigDecimal> values) {
            addCriterion("\"U_IntRate\" not in", values, "uIntrate");
            return (Criteria) this;
        }

        public Criteria andUIntrateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("\"U_IntRate\" between", value1, value2, "uIntrate");
            return (Criteria) this;
        }

        public Criteria andUIntrateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("\"U_IntRate\" not between", value1, value2, "uIntrate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table @MTC_OFPR1
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 06 15:55:22 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table @MTC_OFPR1
     *
     * @mbg.generated Wed Mar 06 15:55:22 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}