package io.mtc.modules.sap.entity;

import java.io.Serializable;

public class BplidPeriodKey implements Serializable {
    /**
     * 表 : @MTC_OFPR1
     * 对应字段 : Code
     */
    private String code;

    /**
     * 表 : @MTC_OFPR1
     * 对应字段 : LineId
     */
    private Integer lineid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table @MTC_OFPR1
     *
     * @mbg.generated Wed Mar 06 15:55:22 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return @MTC_OFPR1.Code：null
     */
    public String getCode() {
        return code;
    }

    /**
     * set method 
     *
     * @param code  null
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * get method 
     *
     * @return @MTC_OFPR1.LineId：null
     */
    public Integer getLineid() {
        return lineid;
    }

    /**
     * set method 
     *
     * @param lineid  null
     */
    public void setLineid(Integer lineid) {
        this.lineid = lineid;
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BplidPeriodKey other = (BplidPeriodKey) that;
        return (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getLineid() == null ? other.getLineid() == null : this.getLineid().equals(other.getLineid()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getLineid() == null) ? 0 : getLineid().hashCode());
        return result;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", code=").append(code);
        sb.append(", lineid=").append(lineid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}