package io.mtc.modules.sap.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class BplidPeriod extends BplidPeriodKey implements Serializable {
    /**
     * 表 : @MTC_OFPR1
     * 对应字段 : Object
     */
    private String object;

    /**
     * 表 : @MTC_OFPR1
     * 对应字段 : LogInst
     */
    private Integer loginst;

    /**
     * 表 : @MTC_OFPR1
     * 对应字段 : U_YearCode
     */
    private String uYearcode;

    /**
     * 表 : @MTC_OFPR1
     * 对应字段 : U_FcCode
     */
    private String uFccode;

    /**
     * 表 : @MTC_OFPR1
     * 对应字段 : U_StDate
     */
    private Date uStdate;

    /**
     * 表 : @MTC_OFPR1
     * 对应字段 : U_EndDate
     */
    private Date uEnddate;

    /**
     * 表 : @MTC_OFPR1
     * 对应字段 : U_FStatus
     */
    private String uFstatus;

    /**
     * 表 : @MTC_OFPR1
     * 对应字段 : U_ChDate
     */
    private Date uChdate;

    /**
     * 表 : @MTC_OFPR1
     * 对应字段 : U_IntRate
     */
    private BigDecimal uIntrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table @MTC_OFPR1
     *
     * @mbg.generated Wed Mar 06 15:55:22 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return @MTC_OFPR1.Object：null
     */
    public String getObject() {
        return object;
    }

    /**
     * set method 
     *
     * @param object  null
     */
    public void setObject(String object) {
        this.object = object == null ? null : object.trim();
    }

    /**
     * get method 
     *
     * @return @MTC_OFPR1.LogInst：null
     */
    public Integer getLoginst() {
        return loginst;
    }

    /**
     * set method 
     *
     * @param loginst  null
     */
    public void setLoginst(Integer loginst) {
        this.loginst = loginst;
    }

    /**
     * get method 
     *
     * @return @MTC_OFPR1.U_YearCode：null
     */
    public String getuYearcode() {
        return uYearcode;
    }

    /**
     * set method 
     *
     * @param uYearcode  null
     */
    public void setuYearcode(String uYearcode) {
        this.uYearcode = uYearcode == null ? null : uYearcode.trim();
    }

    /**
     * get method 
     *
     * @return @MTC_OFPR1.U_FcCode：null
     */
    public String getuFccode() {
        return uFccode;
    }

    /**
     * set method 
     *
     * @param uFccode  null
     */
    public void setuFccode(String uFccode) {
        this.uFccode = uFccode == null ? null : uFccode.trim();
    }

    /**
     * get method 
     *
     * @return @MTC_OFPR1.U_StDate：null
     */
    public Date getuStdate() {
        return uStdate;
    }

    /**
     * set method 
     *
     * @param uStdate  null
     */
    public void setuStdate(Date uStdate) {
        this.uStdate = uStdate;
    }

    /**
     * get method 
     *
     * @return @MTC_OFPR1.U_EndDate：null
     */
    public Date getuEnddate() {
        return uEnddate;
    }

    /**
     * set method 
     *
     * @param uEnddate  null
     */
    public void setuEnddate(Date uEnddate) {
        this.uEnddate = uEnddate;
    }

    /**
     * get method 
     *
     * @return @MTC_OFPR1.U_FStatus：null
     */
    public String getuFstatus() {
        return uFstatus;
    }

    /**
     * set method 
     *
     * @param uFstatus  null
     */
    public void setuFstatus(String uFstatus) {
        this.uFstatus = uFstatus == null ? null : uFstatus.trim();
    }

    /**
     * get method 
     *
     * @return @MTC_OFPR1.U_ChDate：null
     */
    public Date getuChdate() {
        return uChdate;
    }

    /**
     * set method 
     *
     * @param uChdate  null
     */
    public void setuChdate(Date uChdate) {
        this.uChdate = uChdate;
    }

    /**
     * get method 
     *
     * @return @MTC_OFPR1.U_IntRate：null
     */
    public BigDecimal getuIntrate() {
        return uIntrate;
    }

    /**
     * set method 
     *
     * @param uIntrate  null
     */
    public void setuIntrate(BigDecimal uIntrate) {
        this.uIntrate = uIntrate;
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BplidPeriod other = (BplidPeriod) that;
        return (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getLineid() == null ? other.getLineid() == null : this.getLineid().equals(other.getLineid()))
            && (this.getObject() == null ? other.getObject() == null : this.getObject().equals(other.getObject()))
            && (this.getLoginst() == null ? other.getLoginst() == null : this.getLoginst().equals(other.getLoginst()))
            && (this.getuYearcode() == null ? other.getuYearcode() == null : this.getuYearcode().equals(other.getuYearcode()))
            && (this.getuFccode() == null ? other.getuFccode() == null : this.getuFccode().equals(other.getuFccode()))
            && (this.getuStdate() == null ? other.getuStdate() == null : this.getuStdate().equals(other.getuStdate()))
            && (this.getuEnddate() == null ? other.getuEnddate() == null : this.getuEnddate().equals(other.getuEnddate()))
            && (this.getuFstatus() == null ? other.getuFstatus() == null : this.getuFstatus().equals(other.getuFstatus()))
            && (this.getuChdate() == null ? other.getuChdate() == null : this.getuChdate().equals(other.getuChdate()))
            && (this.getuIntrate() == null ? other.getuIntrate() == null : this.getuIntrate().equals(other.getuIntrate()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getLineid() == null) ? 0 : getLineid().hashCode());
        result = prime * result + ((getObject() == null) ? 0 : getObject().hashCode());
        result = prime * result + ((getLoginst() == null) ? 0 : getLoginst().hashCode());
        result = prime * result + ((getuYearcode() == null) ? 0 : getuYearcode().hashCode());
        result = prime * result + ((getuFccode() == null) ? 0 : getuFccode().hashCode());
        result = prime * result + ((getuStdate() == null) ? 0 : getuStdate().hashCode());
        result = prime * result + ((getuEnddate() == null) ? 0 : getuEnddate().hashCode());
        result = prime * result + ((getuFstatus() == null) ? 0 : getuFstatus().hashCode());
        result = prime * result + ((getuChdate() == null) ? 0 : getuChdate().hashCode());
        result = prime * result + ((getuIntrate() == null) ? 0 : getuIntrate().hashCode());
        return result;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", object=").append(object);
        sb.append(", loginst=").append(loginst);
        sb.append(", uYearcode=").append(uYearcode);
        sb.append(", uFccode=").append(uFccode);
        sb.append(", uStdate=").append(uStdate);
        sb.append(", uEnddate=").append(uEnddate);
        sb.append(", uFstatus=").append(uFstatus);
        sb.append(", uChdate=").append(uChdate);
        sb.append(", uIntrate=").append(uIntrate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}