package io.mtc.modules.sap.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class MtcSdDLD2 implements Serializable {
    /**
     * 内部标识
     * 表 : MTC_SD_DLD2
     * 对应字段 : DocEntry
     */
    private Integer docentry;

    /**
     * 收款方式编码
     * 表 : MTC_SD_DLD2
     * 对应字段 : PayCode
     */
    private String paycode;

    /**
     * 收款方式名称
     * 表 : MTC_SD_DLD2
     * 对应字段 : PayMent
     */
    private String payment;

    /**
     * 收款金额
     * 表 : MTC_SD_DLD2
     * 对应字段 : PayAmt
     */
    private BigDecimal payamt;

    /**
     * 收款单号
     * 表 : MTC_SD_DLD2
     * 对应字段 : PayNum
     */
    private String paynum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MTC_SD_DLD2
     *
     * @mbg.generated Thu Mar 07 14:47:32 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return MTC_SD_DLD2.DocEntry：内部标识
     */
    public Integer getDocentry() {
        return docentry;
    }

    /**
     * set method 
     *
     * @param docentry  内部标识
     */
    public void setDocentry(Integer docentry) {
        this.docentry = docentry;
    }

    /**
     * get method 
     *
     * @return MTC_SD_DLD2.PayCode：收款方式编码
     */
    public String getPaycode() {
        return paycode;
    }

    /**
     * set method 
     *
     * @param paycode  收款方式编码
     */
    public void setPaycode(String paycode) {
        this.paycode = paycode == null ? null : paycode.trim();
    }

    /**
     * get method 
     *
     * @return MTC_SD_DLD2.PayMent：收款方式名称
     */
    public String getPayment() {
        return payment;
    }

    /**
     * set method 
     *
     * @param payment  收款方式名称
     */
    public void setPayment(String payment) {
        this.payment = payment == null ? null : payment.trim();
    }

    /**
     * get method 
     *
     * @return MTC_SD_DLD2.PayAmt：收款金额
     */
    public BigDecimal getPayamt() {
        return payamt;
    }

    /**
     * set method 
     *
     * @param payamt  收款金额
     */
    public void setPayamt(BigDecimal payamt) {
        this.payamt = payamt;
    }

    /**
     * get method 
     *
     * @return MTC_SD_DLD2.PayNum：收款单号
     */
    public String getPaynum() {
        return paynum;
    }

    /**
     * set method 
     *
     * @param paynum  收款单号
     */
    public void setPaynum(String paynum) {
        this.paynum = paynum == null ? null : paynum.trim();
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MtcSdDLD2 other = (MtcSdDLD2) that;
        return (this.getDocentry() == null ? other.getDocentry() == null : this.getDocentry().equals(other.getDocentry()))
            && (this.getPaycode() == null ? other.getPaycode() == null : this.getPaycode().equals(other.getPaycode()))
            && (this.getPayment() == null ? other.getPayment() == null : this.getPayment().equals(other.getPayment()))
            && (this.getPayamt() == null ? other.getPayamt() == null : this.getPayamt().equals(other.getPayamt()))
            && (this.getPaynum() == null ? other.getPaynum() == null : this.getPaynum().equals(other.getPaynum()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDocentry() == null) ? 0 : getDocentry().hashCode());
        result = prime * result + ((getPaycode() == null) ? 0 : getPaycode().hashCode());
        result = prime * result + ((getPayment() == null) ? 0 : getPayment().hashCode());
        result = prime * result + ((getPayamt() == null) ? 0 : getPayamt().hashCode());
        result = prime * result + ((getPaynum() == null) ? 0 : getPaynum().hashCode());
        return result;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", docentry=").append(docentry);
        sb.append(", paycode=").append(paycode);
        sb.append(", payment=").append(payment);
        sb.append(", payamt=").append(payamt);
        sb.append(", paynum=").append(paynum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}