package io.mtc.modules.sap.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class MtcSdBJD1 implements Serializable {
    /**
     * 内部标识
     * 表 : MTC_SD_BJD1
     * 对应字段 : DocEntry
     */
    private Integer docentry;

    /**
     * 行号
     * 表 : MTC_SD_BJD1
     * 对应字段 : LineNum
     */
    private Integer linenum;

    /**
     * 产品编号
     * 表 : MTC_SD_BJD1
     * 对应字段 : ItemCode
     */
    private String itemcode;

    /**
     * 产品名称
     * 表 : MTC_SD_BJD1
     * 对应字段 : ItemName
     */
    private String itemname;

    /**
     * 保价单价
     * 表 : MTC_SD_BJD1
     * 对应字段 : Price
     */
    private BigDecimal price;

    /**
     * 包重
     * 表 : MTC_SD_BJD1
     * 对应字段 : Factor1
     */
    private BigDecimal factor1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MTC_SD_BJD1
     *
     * @mbg.generated Mon Apr 29 11:16:22 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method
     *
     * @return MTC_SD_BJD1.DocEntry：内部标识
     */
    public Integer getDocentry() {
        return docentry;
    }

    /**
     * set method
     *
     * @param docentry  内部标识
     */
    public void setDocentry(Integer docentry) {
        this.docentry = docentry;
    }

    /**
     * get method
     *
     * @return MTC_SD_BJD1.LineNum：行号
     */
    public Integer getLinenum() {
        return linenum;
    }

    /**
     * set method
     *
     * @param linenum  行号
     */
    public void setLinenum(Integer linenum) {
        this.linenum = linenum;
    }

    /**
     * get method
     *
     * @return MTC_SD_BJD1.ItemCode：产品编号
     */
    public String getItemcode() {
        return itemcode;
    }

    /**
     * set method
     *
     * @param itemcode  产品编号
     */
    public void setItemcode(String itemcode) {
        this.itemcode = itemcode == null ? null : itemcode.trim();
    }

    /**
     * get method
     *
     * @return MTC_SD_BJD1.ItemName：产品名称
     */
    public String getItemname() {
        return itemname;
    }

    /**
     * set method
     *
     * @param itemname  产品名称
     */
    public void setItemname(String itemname) {
        this.itemname = itemname == null ? null : itemname.trim();
    }

    /**
     * get method
     *
     * @return MTC_SD_BJD1.Price：保价单价
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * set method
     *
     * @param price  保价单价
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * get method
     *
     * @return MTC_SD_BJD1.Factor1：包重
     */
    public BigDecimal getFactor1() {
        return factor1;
    }

    /**
     * set method
     *
     * @param factor1  包重
     */
    public void setFactor1(BigDecimal factor1) {
        this.factor1 = factor1;
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MtcSdBJD1 other = (MtcSdBJD1) that;
        return (this.getDocentry() == null ? other.getDocentry() == null : this.getDocentry().equals(other.getDocentry()))
                && (this.getLinenum() == null ? other.getLinenum() == null : this.getLinenum().equals(other.getLinenum()))
                && (this.getItemcode() == null ? other.getItemcode() == null : this.getItemcode().equals(other.getItemcode()))
                && (this.getItemname() == null ? other.getItemname() == null : this.getItemname().equals(other.getItemname()))
                && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
                && (this.getFactor1() == null ? other.getFactor1() == null : this.getFactor1().equals(other.getFactor1()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDocentry() == null) ? 0 : getDocentry().hashCode());
        result = prime * result + ((getLinenum() == null) ? 0 : getLinenum().hashCode());
        result = prime * result + ((getItemcode() == null) ? 0 : getItemcode().hashCode());
        result = prime * result + ((getItemname() == null) ? 0 : getItemname().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getFactor1() == null) ? 0 : getFactor1().hashCode());
        return result;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", docentry=").append(docentry);
        sb.append(", linenum=").append(linenum);
        sb.append(", itemcode=").append(itemcode);
        sb.append(", itemname=").append(itemname);
        sb.append(", price=").append(price);
        sb.append(", factor1=").append(factor1);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}