package io.mtc.modules.sap.entity;

import io.mtc.modules.sap.constant.Constant;
import org.apache.commons.lang.StringUtils;

import java.io.Serializable;
import java.math.BigDecimal;

public class MtcSdOBJD implements Serializable {
    /**
     * 内部标识
     * 表 : MTC_SD_OBJD
     * 对应字段 : DocEntry
     */
    private Integer docentry;

    /**
     * 单据编号
     * 表 : MTC_SD_OBJD
     * 对应字段 : DocNum
     */
    private Integer docnum;

    /**
     * 分支
     * 表 : MTC_SD_OBJD
     * 对应字段 : BPLId
     */
    private String bplid;

    /**
     * 客户代码
     * 表 : MTC_SD_OBJD
     * 对应字段 : CardCode
     */
    private String cardcode;

    /**
     * 客户名称
     * 表 : MTC_SD_OBJD
     * 对应字段 : CardName
     */
    private String cardname;

    /**
     * 单据日期
     * 表 : MTC_SD_OBJD
     * 对应字段 : DocDate
     */
    private String docdate;

    /**
     * 已使用收款
     * 表 : MTC_SD_OBJD
     * 对应字段 : UsedAmt
     */
    private BigDecimal usedamt;

    /**
     * 还剩余额
     * 表 : MTC_SD_OBJD
     * 对应字段 : LastAmt
     */
    private BigDecimal lastamt;

    /**
     * 单据状态
     * 表 : MTC_SD_OBJD
     * 对应字段 : DocStatus
     */
    private String docstatus;

    /**
     * 创建人
     * 表 : MTC_SD_OBJD
     * 对应字段 : Creator
     */
    private String creator;

    /**
     * 创建时间
     * 表 : MTC_SD_OBJD
     * 对应字段 : CreateTime
     */
    private String createtime;

    /**
     * 更新人
     * 表 : MTC_SD_OBJD
     * 对应字段 : Updator
     */
    private String updator;

    /**
     * 更新时间
     * 表 : MTC_SD_OBJD
     * 对应字段 : UpdateTime
     */
    private String updatetime;

    /**
     * 备注
     * 表 : MTC_SD_OBJD
     * 对应字段 : Remark
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MTC_SD_OBJD
     *
     * @mbg.generated Wed Mar 06 16:47:32 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return MTC_SD_OBJD.DocEntry：内部标识
     */
    public Integer getDocentry() {
        return docentry;
    }

    /**
     * set method 
     *
     * @param docentry  内部标识
     */
    public void setDocentry(Integer docentry) {
        this.docentry = docentry;
    }

    /**
     * get method 
     *
     * @return MTC_SD_OBJD.DocNum：单据编号
     */
    public Integer getDocnum() {
        return docnum;
    }

    /**
     * set method 
     *
     * @param docnum  单据编号
     */
    public void setDocnum(Integer docnum) {
        this.docnum = docnum;
    }

    /**
     * get method 
     *
     * @return MTC_SD_OBJD.BPLId：分支
     */
    public String getBplid() {
        return bplid;
    }

    /**
     * set method 
     *
     * @param bplid  分支
     */
    public void setBplid(String bplid) {
        this.bplid = bplid == null ? null : bplid.trim();
    }

    /**
     * get method 
     *
     * @return MTC_SD_OBJD.CardCode：客户代码
     */
    public String getCardcode() {
        return cardcode;
    }

    /**
     * set method 
     *
     * @param cardcode  客户代码
     */
    public void setCardcode(String cardcode) {
        this.cardcode = cardcode == null ? null : cardcode.trim();
    }

    /**
     * get method 
     *
     * @return MTC_SD_OBJD.CardName：客户名称
     */
    public String getCardname() {
        return cardname;
    }

    /**
     * set method 
     *
     * @param cardname  客户名称
     */
    public void setCardname(String cardname) {
        this.cardname = cardname == null ? null : cardname.trim();
    }

    /**
     * get method 
     *
     * @return MTC_SD_OBJD.DocDate：单据日期
     */
    public String getDocdate() {
        return docdate;
    }

    /**
     * set method 
     *
     * @param docdate  单据日期
     */
    public void setDocdate(String docdate) {
        this.docdate = docdate == null ? null : docdate.trim();
    }

    /**
     * get method 
     *
     * @return MTC_SD_OBJD.UsedAmt：已使用收款
     */
    public BigDecimal getUsedamt() {
        return usedamt;
    }

    /**
     * set method 
     *
     * @param usedamt  已使用收款
     */
    public void setUsedamt(BigDecimal usedamt) {
        this.usedamt = usedamt;
    }

    /**
     * get method 
     *
     * @return MTC_SD_OBJD.LastAmt：还剩余额
     */
    public BigDecimal getLastamt() {
        return lastamt;
    }

    /**
     * set method 
     *
     * @param lastamt  还剩余额
     */
    public void setLastamt(BigDecimal lastamt) {
        this.lastamt = lastamt;
    }

    /**
     * get method 
     *
     * @return MTC_SD_OBJD.DocStatus：单据状态
     */
    public String getDocstatus() {
        return docstatus;
    }

    /**
     * set method 
     *
     * @param docstatus  单据状态
     */
    public void setDocstatus(String docstatus) {
        this.docstatus = docstatus == null ? null : docstatus.trim();
    }

    /**
     * get method 
     *
     * @return MTC_SD_OBJD.Creator：创建人
     */
    public String getCreator() {
        return creator;
    }

    /**
     * set method 
     *
     * @param creator  创建人
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * get method 
     *
     * @return MTC_SD_OBJD.CreateTime：创建时间
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * set method 
     *
     * @param createtime  创建时间
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * get method 
     *
     * @return MTC_SD_OBJD.Updator：更新人
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * set method 
     *
     * @param updator  更新人
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * get method 
     *
     * @return MTC_SD_OBJD.UpdateTime：更新时间
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * set method 
     *
     * @param updatetime  更新时间
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }

    /**
     * get method 
     *
     * @return MTC_SD_OBJD.Remark：备注
     */
    public String getRemark() {
        return remark;
    }

    /**
     * set method 
     *
     * @param remark  备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public String getDocStatusName(){
        if(StringUtils.isNotEmpty(docstatus)){
            return Constant.DesOrderDocStatusEnum.value(docstatus).toString();
        }
        return null;
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MtcSdOBJD other = (MtcSdOBJD) that;
        return (this.getDocentry() == null ? other.getDocentry() == null : this.getDocentry().equals(other.getDocentry()))
            && (this.getDocnum() == null ? other.getDocnum() == null : this.getDocnum().equals(other.getDocnum()))
            && (this.getBplid() == null ? other.getBplid() == null : this.getBplid().equals(other.getBplid()))
            && (this.getCardcode() == null ? other.getCardcode() == null : this.getCardcode().equals(other.getCardcode()))
            && (this.getCardname() == null ? other.getCardname() == null : this.getCardname().equals(other.getCardname()))
            && (this.getDocdate() == null ? other.getDocdate() == null : this.getDocdate().equals(other.getDocdate()))
            && (this.getUsedamt() == null ? other.getUsedamt() == null : this.getUsedamt().equals(other.getUsedamt()))
            && (this.getLastamt() == null ? other.getLastamt() == null : this.getLastamt().equals(other.getLastamt()))
            && (this.getDocstatus() == null ? other.getDocstatus() == null : this.getDocstatus().equals(other.getDocstatus()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getUpdator() == null ? other.getUpdator() == null : this.getUpdator().equals(other.getUpdator()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDocentry() == null) ? 0 : getDocentry().hashCode());
        result = prime * result + ((getDocnum() == null) ? 0 : getDocnum().hashCode());
        result = prime * result + ((getBplid() == null) ? 0 : getBplid().hashCode());
        result = prime * result + ((getCardcode() == null) ? 0 : getCardcode().hashCode());
        result = prime * result + ((getCardname() == null) ? 0 : getCardname().hashCode());
        result = prime * result + ((getDocdate() == null) ? 0 : getDocdate().hashCode());
        result = prime * result + ((getUsedamt() == null) ? 0 : getUsedamt().hashCode());
        result = prime * result + ((getLastamt() == null) ? 0 : getLastamt().hashCode());
        result = prime * result + ((getDocstatus() == null) ? 0 : getDocstatus().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getUpdator() == null) ? 0 : getUpdator().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", docentry=").append(docentry);
        sb.append(", docnum=").append(docnum);
        sb.append(", bplid=").append(bplid);
        sb.append(", cardcode=").append(cardcode);
        sb.append(", cardname=").append(cardname);
        sb.append(", docdate=").append(docdate);
        sb.append(", usedamt=").append(usedamt);
        sb.append(", lastamt=").append(lastamt);
        sb.append(", docstatus=").append(docstatus);
        sb.append(", creator=").append(creator);
        sb.append(", createtime=").append(createtime);
        sb.append(", updator=").append(updator);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}