package io.mtc.modules.sap.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class MtcSdBJD2Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MTC_SD_BJD2
     *
     * @mbg.generated Thu Mar 07 14:47:32 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MTC_SD_BJD2
     *
     * @mbg.generated Thu Mar 07 14:47:32 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MTC_SD_BJD2
     *
     * @mbg.generated Thu Mar 07 14:47:32 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     *
     */
    public MtcSdBJD2Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *
     * @param orderByClause
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *
     * @param distinct
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     *
     * @param criteria
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     *
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MTC_SD_BJD2
     *
     * @mbg.generated Thu Mar 07 14:47:32 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDocentryIsNull() {
            addCriterion("\"DocEntry\" is null");
            return (Criteria) this;
        }

        public Criteria andDocentryIsNotNull() {
            addCriterion("\"DocEntry\" is not null");
            return (Criteria) this;
        }

        public Criteria andDocentryEqualTo(Integer value) {
            addCriterion("\"DocEntry\" =", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryNotEqualTo(Integer value) {
            addCriterion("\"DocEntry\" <>", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryGreaterThan(Integer value) {
            addCriterion("\"DocEntry\" >", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"DocEntry\" >=", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryLessThan(Integer value) {
            addCriterion("\"DocEntry\" <", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryLessThanOrEqualTo(Integer value) {
            addCriterion("\"DocEntry\" <=", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryIn(List<Integer> values) {
            addCriterion("\"DocEntry\" in", values, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryNotIn(List<Integer> values) {
            addCriterion("\"DocEntry\" not in", values, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryBetween(Integer value1, Integer value2) {
            addCriterion("\"DocEntry\" between", value1, value2, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryNotBetween(Integer value1, Integer value2) {
            addCriterion("\"DocEntry\" not between", value1, value2, "docentry");
            return (Criteria) this;
        }

        public Criteria andPaycodeIsNull() {
            addCriterion("\"PayCode\" is null");
            return (Criteria) this;
        }

        public Criteria andPaycodeIsNotNull() {
            addCriterion("\"PayCode\" is not null");
            return (Criteria) this;
        }

        public Criteria andPaycodeEqualTo(String value) {
            addCriterion("\"PayCode\" =", value, "paycode");
            return (Criteria) this;
        }

        public Criteria andPaycodeNotEqualTo(String value) {
            addCriterion("\"PayCode\" <>", value, "paycode");
            return (Criteria) this;
        }

        public Criteria andPaycodeGreaterThan(String value) {
            addCriterion("\"PayCode\" >", value, "paycode");
            return (Criteria) this;
        }

        public Criteria andPaycodeGreaterThanOrEqualTo(String value) {
            addCriterion("\"PayCode\" >=", value, "paycode");
            return (Criteria) this;
        }

        public Criteria andPaycodeLessThan(String value) {
            addCriterion("\"PayCode\" <", value, "paycode");
            return (Criteria) this;
        }

        public Criteria andPaycodeLessThanOrEqualTo(String value) {
            addCriterion("\"PayCode\" <=", value, "paycode");
            return (Criteria) this;
        }

        public Criteria andPaycodeLike(String value) {
            addCriterion("\"PayCode\" like", value, "paycode");
            return (Criteria) this;
        }

        public Criteria andPaycodeNotLike(String value) {
            addCriterion("\"PayCode\" not like", value, "paycode");
            return (Criteria) this;
        }

        public Criteria andPaycodeIn(List<String> values) {
            addCriterion("\"PayCode\" in", values, "paycode");
            return (Criteria) this;
        }

        public Criteria andPaycodeNotIn(List<String> values) {
            addCriterion("\"PayCode\" not in", values, "paycode");
            return (Criteria) this;
        }

        public Criteria andPaycodeBetween(String value1, String value2) {
            addCriterion("\"PayCode\" between", value1, value2, "paycode");
            return (Criteria) this;
        }

        public Criteria andPaycodeNotBetween(String value1, String value2) {
            addCriterion("\"PayCode\" not between", value1, value2, "paycode");
            return (Criteria) this;
        }

        public Criteria andPaymentIsNull() {
            addCriterion("\"PayMent\" is null");
            return (Criteria) this;
        }

        public Criteria andPaymentIsNotNull() {
            addCriterion("\"PayMent\" is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentEqualTo(String value) {
            addCriterion("\"PayMent\" =", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentNotEqualTo(String value) {
            addCriterion("\"PayMent\" <>", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentGreaterThan(String value) {
            addCriterion("\"PayMent\" >", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentGreaterThanOrEqualTo(String value) {
            addCriterion("\"PayMent\" >=", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentLessThan(String value) {
            addCriterion("\"PayMent\" <", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentLessThanOrEqualTo(String value) {
            addCriterion("\"PayMent\" <=", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentLike(String value) {
            addCriterion("\"PayMent\" like", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentNotLike(String value) {
            addCriterion("\"PayMent\" not like", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentIn(List<String> values) {
            addCriterion("\"PayMent\" in", values, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentNotIn(List<String> values) {
            addCriterion("\"PayMent\" not in", values, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentBetween(String value1, String value2) {
            addCriterion("\"PayMent\" between", value1, value2, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentNotBetween(String value1, String value2) {
            addCriterion("\"PayMent\" not between", value1, value2, "payment");
            return (Criteria) this;
        }

        public Criteria andPayamtIsNull() {
            addCriterion("\"PayAmt\" is null");
            return (Criteria) this;
        }

        public Criteria andPayamtIsNotNull() {
            addCriterion("\"PayAmt\" is not null");
            return (Criteria) this;
        }

        public Criteria andPayamtEqualTo(BigDecimal value) {
            addCriterion("\"PayAmt\" =", value, "payamt");
            return (Criteria) this;
        }

        public Criteria andPayamtNotEqualTo(BigDecimal value) {
            addCriterion("\"PayAmt\" <>", value, "payamt");
            return (Criteria) this;
        }

        public Criteria andPayamtGreaterThan(BigDecimal value) {
            addCriterion("\"PayAmt\" >", value, "payamt");
            return (Criteria) this;
        }

        public Criteria andPayamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("\"PayAmt\" >=", value, "payamt");
            return (Criteria) this;
        }

        public Criteria andPayamtLessThan(BigDecimal value) {
            addCriterion("\"PayAmt\" <", value, "payamt");
            return (Criteria) this;
        }

        public Criteria andPayamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("\"PayAmt\" <=", value, "payamt");
            return (Criteria) this;
        }

        public Criteria andPayamtIn(List<BigDecimal> values) {
            addCriterion("\"PayAmt\" in", values, "payamt");
            return (Criteria) this;
        }

        public Criteria andPayamtNotIn(List<BigDecimal> values) {
            addCriterion("\"PayAmt\" not in", values, "payamt");
            return (Criteria) this;
        }

        public Criteria andPayamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("\"PayAmt\" between", value1, value2, "payamt");
            return (Criteria) this;
        }

        public Criteria andPayamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("\"PayAmt\" not between", value1, value2, "payamt");
            return (Criteria) this;
        }

        public Criteria andPaynumIsNull() {
            addCriterion("\"PayNum\" is null");
            return (Criteria) this;
        }

        public Criteria andPaynumIsNotNull() {
            addCriterion("\"PayNum\" is not null");
            return (Criteria) this;
        }

        public Criteria andPaynumEqualTo(String value) {
            addCriterion("\"PayNum\" =", value, "paynum");
            return (Criteria) this;
        }

        public Criteria andPaynumNotEqualTo(String value) {
            addCriterion("\"PayNum\" <>", value, "paynum");
            return (Criteria) this;
        }

        public Criteria andPaynumGreaterThan(String value) {
            addCriterion("\"PayNum\" >", value, "paynum");
            return (Criteria) this;
        }

        public Criteria andPaynumGreaterThanOrEqualTo(String value) {
            addCriterion("\"PayNum\" >=", value, "paynum");
            return (Criteria) this;
        }

        public Criteria andPaynumLessThan(String value) {
            addCriterion("\"PayNum\" <", value, "paynum");
            return (Criteria) this;
        }

        public Criteria andPaynumLessThanOrEqualTo(String value) {
            addCriterion("\"PayNum\" <=", value, "paynum");
            return (Criteria) this;
        }

        public Criteria andPaynumLike(String value) {
            addCriterion("\"PayNum\" like", value, "paynum");
            return (Criteria) this;
        }

        public Criteria andPaynumNotLike(String value) {
            addCriterion("\"PayNum\" not like", value, "paynum");
            return (Criteria) this;
        }

        public Criteria andPaynumIn(List<String> values) {
            addCriterion("\"PayNum\" in", values, "paynum");
            return (Criteria) this;
        }

        public Criteria andPaynumNotIn(List<String> values) {
            addCriterion("\"PayNum\" not in", values, "paynum");
            return (Criteria) this;
        }

        public Criteria andPaynumBetween(String value1, String value2) {
            addCriterion("\"PayNum\" between", value1, value2, "paynum");
            return (Criteria) this;
        }

        public Criteria andPaynumNotBetween(String value1, String value2) {
            addCriterion("\"PayNum\" not between", value1, value2, "paynum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MTC_SD_BJD2
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 07 14:47:32 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MTC_SD_BJD2
     *
     * @mbg.generated Thu Mar 07 14:47:32 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}