package io.mtc.modules.sap.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class MtcSdBJD1Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MTC_SD_BJD1
     *
     * @mbg.generated Mon Apr 29 11:16:22 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MTC_SD_BJD1
     *
     * @mbg.generated Mon Apr 29 11:16:22 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MTC_SD_BJD1
     *
     * @mbg.generated Mon Apr 29 11:16:22 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     *
     */
    public MtcSdBJD1Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * @param orderByClause
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * @param distinct
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * @param criteria
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     *
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MTC_SD_BJD1
     *
     * @mbg.generated Mon Apr 29 11:16:22 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDocentryIsNull() {
            addCriterion("\"DocEntry\" is null");
            return (Criteria) this;
        }

        public Criteria andDocentryIsNotNull() {
            addCriterion("\"DocEntry\" is not null");
            return (Criteria) this;
        }

        public Criteria andDocentryEqualTo(Integer value) {
            addCriterion("\"DocEntry\" =", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryNotEqualTo(Integer value) {
            addCriterion("\"DocEntry\" <>", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryGreaterThan(Integer value) {
            addCriterion("\"DocEntry\" >", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"DocEntry\" >=", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryLessThan(Integer value) {
            addCriterion("\"DocEntry\" <", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryLessThanOrEqualTo(Integer value) {
            addCriterion("\"DocEntry\" <=", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryIn(List<Integer> values) {
            addCriterion("\"DocEntry\" in", values, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryNotIn(List<Integer> values) {
            addCriterion("\"DocEntry\" not in", values, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryBetween(Integer value1, Integer value2) {
            addCriterion("\"DocEntry\" between", value1, value2, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryNotBetween(Integer value1, Integer value2) {
            addCriterion("\"DocEntry\" not between", value1, value2, "docentry");
            return (Criteria) this;
        }

        public Criteria andLinenumIsNull() {
            addCriterion("\"LineNum\" is null");
            return (Criteria) this;
        }

        public Criteria andLinenumIsNotNull() {
            addCriterion("\"LineNum\" is not null");
            return (Criteria) this;
        }

        public Criteria andLinenumEqualTo(Integer value) {
            addCriterion("\"LineNum\" =", value, "linenum");
            return (Criteria) this;
        }

        public Criteria andLinenumNotEqualTo(Integer value) {
            addCriterion("\"LineNum\" <>", value, "linenum");
            return (Criteria) this;
        }

        public Criteria andLinenumGreaterThan(Integer value) {
            addCriterion("\"LineNum\" >", value, "linenum");
            return (Criteria) this;
        }

        public Criteria andLinenumGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"LineNum\" >=", value, "linenum");
            return (Criteria) this;
        }

        public Criteria andLinenumLessThan(Integer value) {
            addCriterion("\"LineNum\" <", value, "linenum");
            return (Criteria) this;
        }

        public Criteria andLinenumLessThanOrEqualTo(Integer value) {
            addCriterion("\"LineNum\" <=", value, "linenum");
            return (Criteria) this;
        }

        public Criteria andLinenumIn(List<Integer> values) {
            addCriterion("\"LineNum\" in", values, "linenum");
            return (Criteria) this;
        }

        public Criteria andLinenumNotIn(List<Integer> values) {
            addCriterion("\"LineNum\" not in", values, "linenum");
            return (Criteria) this;
        }

        public Criteria andLinenumBetween(Integer value1, Integer value2) {
            addCriterion("\"LineNum\" between", value1, value2, "linenum");
            return (Criteria) this;
        }

        public Criteria andLinenumNotBetween(Integer value1, Integer value2) {
            addCriterion("\"LineNum\" not between", value1, value2, "linenum");
            return (Criteria) this;
        }

        public Criteria andItemcodeIsNull() {
            addCriterion("\"ItemCode\" is null");
            return (Criteria) this;
        }

        public Criteria andItemcodeIsNotNull() {
            addCriterion("\"ItemCode\" is not null");
            return (Criteria) this;
        }

        public Criteria andItemcodeEqualTo(String value) {
            addCriterion("\"ItemCode\" =", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeNotEqualTo(String value) {
            addCriterion("\"ItemCode\" <>", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeGreaterThan(String value) {
            addCriterion("\"ItemCode\" >", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeGreaterThanOrEqualTo(String value) {
            addCriterion("\"ItemCode\" >=", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeLessThan(String value) {
            addCriterion("\"ItemCode\" <", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeLessThanOrEqualTo(String value) {
            addCriterion("\"ItemCode\" <=", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeLike(String value) {
            addCriterion("\"ItemCode\" like", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeNotLike(String value) {
            addCriterion("\"ItemCode\" not like", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeIn(List<String> values) {
            addCriterion("\"ItemCode\" in", values, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeNotIn(List<String> values) {
            addCriterion("\"ItemCode\" not in", values, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeBetween(String value1, String value2) {
            addCriterion("\"ItemCode\" between", value1, value2, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeNotBetween(String value1, String value2) {
            addCriterion("\"ItemCode\" not between", value1, value2, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemnameIsNull() {
            addCriterion("\"ItemName\" is null");
            return (Criteria) this;
        }

        public Criteria andItemnameIsNotNull() {
            addCriterion("\"ItemName\" is not null");
            return (Criteria) this;
        }

        public Criteria andItemnameEqualTo(String value) {
            addCriterion("\"ItemName\" =", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameNotEqualTo(String value) {
            addCriterion("\"ItemName\" <>", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameGreaterThan(String value) {
            addCriterion("\"ItemName\" >", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameGreaterThanOrEqualTo(String value) {
            addCriterion("\"ItemName\" >=", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameLessThan(String value) {
            addCriterion("\"ItemName\" <", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameLessThanOrEqualTo(String value) {
            addCriterion("\"ItemName\" <=", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameLike(String value) {
            addCriterion("\"ItemName\" like", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameNotLike(String value) {
            addCriterion("\"ItemName\" not like", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameIn(List<String> values) {
            addCriterion("\"ItemName\" in", values, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameNotIn(List<String> values) {
            addCriterion("\"ItemName\" not in", values, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameBetween(String value1, String value2) {
            addCriterion("\"ItemName\" between", value1, value2, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameNotBetween(String value1, String value2) {
            addCriterion("\"ItemName\" not between", value1, value2, "itemname");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("\"Price\" is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("\"Price\" is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("\"Price\" =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("\"Price\" <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("\"Price\" >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("\"Price\" >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("\"Price\" <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("\"Price\" <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("\"Price\" in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("\"Price\" not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("\"Price\" between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("\"Price\" not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andFactor1IsNull() {
            addCriterion("\"Factor1\" is null");
            return (Criteria) this;
        }

        public Criteria andFactor1IsNotNull() {
            addCriterion("\"Factor1\" is not null");
            return (Criteria) this;
        }

        public Criteria andFactor1EqualTo(BigDecimal value) {
            addCriterion("\"Factor1\" =", value, "factor1");
            return (Criteria) this;
        }

        public Criteria andFactor1NotEqualTo(BigDecimal value) {
            addCriterion("\"Factor1\" <>", value, "factor1");
            return (Criteria) this;
        }

        public Criteria andFactor1GreaterThan(BigDecimal value) {
            addCriterion("\"Factor1\" >", value, "factor1");
            return (Criteria) this;
        }

        public Criteria andFactor1GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("\"Factor1\" >=", value, "factor1");
            return (Criteria) this;
        }

        public Criteria andFactor1LessThan(BigDecimal value) {
            addCriterion("\"Factor1\" <", value, "factor1");
            return (Criteria) this;
        }

        public Criteria andFactor1LessThanOrEqualTo(BigDecimal value) {
            addCriterion("\"Factor1\" <=", value, "factor1");
            return (Criteria) this;
        }

        public Criteria andFactor1In(List<BigDecimal> values) {
            addCriterion("\"Factor1\" in", values, "factor1");
            return (Criteria) this;
        }

        public Criteria andFactor1NotIn(List<BigDecimal> values) {
            addCriterion("\"Factor1\" not in", values, "factor1");
            return (Criteria) this;
        }

        public Criteria andFactor1Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("\"Factor1\" between", value1, value2, "factor1");
            return (Criteria) this;
        }

        public Criteria andFactor1NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("\"Factor1\" not between", value1, value2, "factor1");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MTC_SD_BJD1
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 29 11:16:22 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MTC_SD_BJD1
     *
     * @mbg.generated Mon Apr 29 11:16:22 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}