package io.mtc.modules.sap.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class MtcSdOBJDExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MTC_SD_OBJD
     *
     * @mbg.generated Wed Mar 06 16:47:32 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MTC_SD_OBJD
     *
     * @mbg.generated Wed Mar 06 16:47:32 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MTC_SD_OBJD
     *
     * @mbg.generated Wed Mar 06 16:47:32 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     *
     */
    public MtcSdOBJDExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *
     * @param orderByClause
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *
     * @param distinct
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     *
     * @param criteria
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     *
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MTC_SD_OBJD
     *
     * @mbg.generated Wed Mar 06 16:47:32 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDocentryIsNull() {
            addCriterion("\"DocEntry\" is null");
            return (Criteria) this;
        }

        public Criteria andDocentryIsNotNull() {
            addCriterion("\"DocEntry\" is not null");
            return (Criteria) this;
        }

        public Criteria andDocentryEqualTo(Integer value) {
            addCriterion("\"DocEntry\" =", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryNotEqualTo(Integer value) {
            addCriterion("\"DocEntry\" <>", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryGreaterThan(Integer value) {
            addCriterion("\"DocEntry\" >", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"DocEntry\" >=", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryLessThan(Integer value) {
            addCriterion("\"DocEntry\" <", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryLessThanOrEqualTo(Integer value) {
            addCriterion("\"DocEntry\" <=", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryIn(List<Integer> values) {
            addCriterion("\"DocEntry\" in", values, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryNotIn(List<Integer> values) {
            addCriterion("\"DocEntry\" not in", values, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryBetween(Integer value1, Integer value2) {
            addCriterion("\"DocEntry\" between", value1, value2, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryNotBetween(Integer value1, Integer value2) {
            addCriterion("\"DocEntry\" not between", value1, value2, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocnumIsNull() {
            addCriterion("\"DocNum\" is null");
            return (Criteria) this;
        }

        public Criteria andDocnumIsNotNull() {
            addCriterion("\"DocNum\" is not null");
            return (Criteria) this;
        }

        public Criteria andDocnumEqualTo(Integer value) {
            addCriterion("\"DocNum\" =", value, "docnum");
            return (Criteria) this;
        }

        public Criteria andDocnumNotEqualTo(Integer value) {
            addCriterion("\"DocNum\" <>", value, "docnum");
            return (Criteria) this;
        }

        public Criteria andDocnumGreaterThan(Integer value) {
            addCriterion("\"DocNum\" >", value, "docnum");
            return (Criteria) this;
        }

        public Criteria andDocnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"DocNum\" >=", value, "docnum");
            return (Criteria) this;
        }

        public Criteria andDocnumLessThan(Integer value) {
            addCriterion("\"DocNum\" <", value, "docnum");
            return (Criteria) this;
        }

        public Criteria andDocnumLessThanOrEqualTo(Integer value) {
            addCriterion("\"DocNum\" <=", value, "docnum");
            return (Criteria) this;
        }

        public Criteria andDocnumIn(List<Integer> values) {
            addCriterion("\"DocNum\" in", values, "docnum");
            return (Criteria) this;
        }

        public Criteria andDocnumNotIn(List<Integer> values) {
            addCriterion("\"DocNum\" not in", values, "docnum");
            return (Criteria) this;
        }

        public Criteria andDocnumBetween(Integer value1, Integer value2) {
            addCriterion("\"DocNum\" between", value1, value2, "docnum");
            return (Criteria) this;
        }

        public Criteria andDocnumNotBetween(Integer value1, Integer value2) {
            addCriterion("\"DocNum\" not between", value1, value2, "docnum");
            return (Criteria) this;
        }

        public Criteria andBplidIsNull() {
            addCriterion("\"BPLId\" is null");
            return (Criteria) this;
        }

        public Criteria andBplidIsNotNull() {
            addCriterion("\"BPLId\" is not null");
            return (Criteria) this;
        }

        public Criteria andBplidEqualTo(String value) {
            addCriterion("\"BPLId\" =", value, "bplid");
            return (Criteria) this;
        }

        public Criteria andBplidNotEqualTo(String value) {
            addCriterion("\"BPLId\" <>", value, "bplid");
            return (Criteria) this;
        }

        public Criteria andBplidGreaterThan(String value) {
            addCriterion("\"BPLId\" >", value, "bplid");
            return (Criteria) this;
        }

        public Criteria andBplidGreaterThanOrEqualTo(String value) {
            addCriterion("\"BPLId\" >=", value, "bplid");
            return (Criteria) this;
        }

        public Criteria andBplidLessThan(String value) {
            addCriterion("\"BPLId\" <", value, "bplid");
            return (Criteria) this;
        }

        public Criteria andBplidLessThanOrEqualTo(String value) {
            addCriterion("\"BPLId\" <=", value, "bplid");
            return (Criteria) this;
        }

        public Criteria andBplidLike(String value) {
            addCriterion("\"BPLId\" like", value, "bplid");
            return (Criteria) this;
        }

        public Criteria andBplidNotLike(String value) {
            addCriterion("\"BPLId\" not like", value, "bplid");
            return (Criteria) this;
        }

        public Criteria andBplidIn(List<String> values) {
            addCriterion("\"BPLId\" in", values, "bplid");
            return (Criteria) this;
        }

        public Criteria andBplidNotIn(List<String> values) {
            addCriterion("\"BPLId\" not in", values, "bplid");
            return (Criteria) this;
        }

        public Criteria andBplidBetween(String value1, String value2) {
            addCriterion("\"BPLId\" between", value1, value2, "bplid");
            return (Criteria) this;
        }

        public Criteria andBplidNotBetween(String value1, String value2) {
            addCriterion("\"BPLId\" not between", value1, value2, "bplid");
            return (Criteria) this;
        }

        public Criteria andCardcodeIsNull() {
            addCriterion("\"CardCode\" is null");
            return (Criteria) this;
        }

        public Criteria andCardcodeIsNotNull() {
            addCriterion("\"CardCode\" is not null");
            return (Criteria) this;
        }

        public Criteria andCardcodeEqualTo(String value) {
            addCriterion("\"CardCode\" =", value, "cardcode");
            return (Criteria) this;
        }

        public Criteria andCardcodeNotEqualTo(String value) {
            addCriterion("\"CardCode\" <>", value, "cardcode");
            return (Criteria) this;
        }

        public Criteria andCardcodeGreaterThan(String value) {
            addCriterion("\"CardCode\" >", value, "cardcode");
            return (Criteria) this;
        }

        public Criteria andCardcodeGreaterThanOrEqualTo(String value) {
            addCriterion("\"CardCode\" >=", value, "cardcode");
            return (Criteria) this;
        }

        public Criteria andCardcodeLessThan(String value) {
            addCriterion("\"CardCode\" <", value, "cardcode");
            return (Criteria) this;
        }

        public Criteria andCardcodeLessThanOrEqualTo(String value) {
            addCriterion("\"CardCode\" <=", value, "cardcode");
            return (Criteria) this;
        }

        public Criteria andCardcodeLike(String value) {
            addCriterion("\"CardCode\" like", value, "cardcode");
            return (Criteria) this;
        }

        public Criteria andCardcodeNotLike(String value) {
            addCriterion("\"CardCode\" not like", value, "cardcode");
            return (Criteria) this;
        }

        public Criteria andCardcodeIn(List<String> values) {
            addCriterion("\"CardCode\" in", values, "cardcode");
            return (Criteria) this;
        }

        public Criteria andCardcodeNotIn(List<String> values) {
            addCriterion("\"CardCode\" not in", values, "cardcode");
            return (Criteria) this;
        }

        public Criteria andCardcodeBetween(String value1, String value2) {
            addCriterion("\"CardCode\" between", value1, value2, "cardcode");
            return (Criteria) this;
        }

        public Criteria andCardcodeNotBetween(String value1, String value2) {
            addCriterion("\"CardCode\" not between", value1, value2, "cardcode");
            return (Criteria) this;
        }

        public Criteria andCardnameIsNull() {
            addCriterion("\"CardName\" is null");
            return (Criteria) this;
        }

        public Criteria andCardnameIsNotNull() {
            addCriterion("\"CardName\" is not null");
            return (Criteria) this;
        }

        public Criteria andCardnameEqualTo(String value) {
            addCriterion("\"CardName\" =", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameNotEqualTo(String value) {
            addCriterion("\"CardName\" <>", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameGreaterThan(String value) {
            addCriterion("\"CardName\" >", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameGreaterThanOrEqualTo(String value) {
            addCriterion("\"CardName\" >=", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameLessThan(String value) {
            addCriterion("\"CardName\" <", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameLessThanOrEqualTo(String value) {
            addCriterion("\"CardName\" <=", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameLike(String value) {
            addCriterion("\"CardName\" like", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameNotLike(String value) {
            addCriterion("\"CardName\" not like", value, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameIn(List<String> values) {
            addCriterion("\"CardName\" in", values, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameNotIn(List<String> values) {
            addCriterion("\"CardName\" not in", values, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameBetween(String value1, String value2) {
            addCriterion("\"CardName\" between", value1, value2, "cardname");
            return (Criteria) this;
        }

        public Criteria andCardnameNotBetween(String value1, String value2) {
            addCriterion("\"CardName\" not between", value1, value2, "cardname");
            return (Criteria) this;
        }

        public Criteria andDocdateIsNull() {
            addCriterion("\"DocDate\" is null");
            return (Criteria) this;
        }

        public Criteria andDocdateIsNotNull() {
            addCriterion("\"DocDate\" is not null");
            return (Criteria) this;
        }

        public Criteria andDocdateEqualTo(String value) {
            addCriterion("\"DocDate\" =", value, "docdate");
            return (Criteria) this;
        }

        public Criteria andDocdateNotEqualTo(String value) {
            addCriterion("\"DocDate\" <>", value, "docdate");
            return (Criteria) this;
        }

        public Criteria andDocdateGreaterThan(String value) {
            addCriterion("\"DocDate\" >", value, "docdate");
            return (Criteria) this;
        }

        public Criteria andDocdateGreaterThanOrEqualTo(String value) {
            addCriterion("\"DocDate\" >=", value, "docdate");
            return (Criteria) this;
        }

        public Criteria andDocdateLessThan(String value) {
            addCriterion("\"DocDate\" <", value, "docdate");
            return (Criteria) this;
        }

        public Criteria andDocdateLessThanOrEqualTo(String value) {
            addCriterion("\"DocDate\" <=", value, "docdate");
            return (Criteria) this;
        }

        public Criteria andDocdateLike(String value) {
            addCriterion("\"DocDate\" like", value, "docdate");
            return (Criteria) this;
        }

        public Criteria andDocdateNotLike(String value) {
            addCriterion("\"DocDate\" not like", value, "docdate");
            return (Criteria) this;
        }

        public Criteria andDocdateIn(List<String> values) {
            addCriterion("\"DocDate\" in", values, "docdate");
            return (Criteria) this;
        }

        public Criteria andDocdateNotIn(List<String> values) {
            addCriterion("\"DocDate\" not in", values, "docdate");
            return (Criteria) this;
        }

        public Criteria andDocdateBetween(String value1, String value2) {
            addCriterion("\"DocDate\" between", value1, value2, "docdate");
            return (Criteria) this;
        }

        public Criteria andDocdateNotBetween(String value1, String value2) {
            addCriterion("\"DocDate\" not between", value1, value2, "docdate");
            return (Criteria) this;
        }

        public Criteria andUsedamtIsNull() {
            addCriterion("\"UsedAmt\" is null");
            return (Criteria) this;
        }

        public Criteria andUsedamtIsNotNull() {
            addCriterion("\"UsedAmt\" is not null");
            return (Criteria) this;
        }

        public Criteria andUsedamtEqualTo(BigDecimal value) {
            addCriterion("\"UsedAmt\" =", value, "usedamt");
            return (Criteria) this;
        }

        public Criteria andUsedamtNotEqualTo(BigDecimal value) {
            addCriterion("\"UsedAmt\" <>", value, "usedamt");
            return (Criteria) this;
        }

        public Criteria andUsedamtGreaterThan(BigDecimal value) {
            addCriterion("\"UsedAmt\" >", value, "usedamt");
            return (Criteria) this;
        }

        public Criteria andUsedamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("\"UsedAmt\" >=", value, "usedamt");
            return (Criteria) this;
        }

        public Criteria andUsedamtLessThan(BigDecimal value) {
            addCriterion("\"UsedAmt\" <", value, "usedamt");
            return (Criteria) this;
        }

        public Criteria andUsedamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("\"UsedAmt\" <=", value, "usedamt");
            return (Criteria) this;
        }

        public Criteria andUsedamtIn(List<BigDecimal> values) {
            addCriterion("\"UsedAmt\" in", values, "usedamt");
            return (Criteria) this;
        }

        public Criteria andUsedamtNotIn(List<BigDecimal> values) {
            addCriterion("\"UsedAmt\" not in", values, "usedamt");
            return (Criteria) this;
        }

        public Criteria andUsedamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("\"UsedAmt\" between", value1, value2, "usedamt");
            return (Criteria) this;
        }

        public Criteria andUsedamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("\"UsedAmt\" not between", value1, value2, "usedamt");
            return (Criteria) this;
        }

        public Criteria andLastamtIsNull() {
            addCriterion("\"LastAmt\" is null");
            return (Criteria) this;
        }

        public Criteria andLastamtIsNotNull() {
            addCriterion("\"LastAmt\" is not null");
            return (Criteria) this;
        }

        public Criteria andLastamtEqualTo(BigDecimal value) {
            addCriterion("\"LastAmt\" =", value, "lastamt");
            return (Criteria) this;
        }

        public Criteria andLastamtNotEqualTo(BigDecimal value) {
            addCriterion("\"LastAmt\" <>", value, "lastamt");
            return (Criteria) this;
        }

        public Criteria andLastamtGreaterThan(BigDecimal value) {
            addCriterion("\"LastAmt\" >", value, "lastamt");
            return (Criteria) this;
        }

        public Criteria andLastamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("\"LastAmt\" >=", value, "lastamt");
            return (Criteria) this;
        }

        public Criteria andLastamtLessThan(BigDecimal value) {
            addCriterion("\"LastAmt\" <", value, "lastamt");
            return (Criteria) this;
        }

        public Criteria andLastamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("\"LastAmt\" <=", value, "lastamt");
            return (Criteria) this;
        }

        public Criteria andLastamtIn(List<BigDecimal> values) {
            addCriterion("\"LastAmt\" in", values, "lastamt");
            return (Criteria) this;
        }

        public Criteria andLastamtNotIn(List<BigDecimal> values) {
            addCriterion("\"LastAmt\" not in", values, "lastamt");
            return (Criteria) this;
        }

        public Criteria andLastamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("\"LastAmt\" between", value1, value2, "lastamt");
            return (Criteria) this;
        }

        public Criteria andLastamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("\"LastAmt\" not between", value1, value2, "lastamt");
            return (Criteria) this;
        }

        public Criteria andDocstatusIsNull() {
            addCriterion("\"DocStatus\" is null");
            return (Criteria) this;
        }

        public Criteria andDocstatusIsNotNull() {
            addCriterion("\"DocStatus\" is not null");
            return (Criteria) this;
        }

        public Criteria andDocstatusEqualTo(String value) {
            addCriterion("\"DocStatus\" =", value, "docstatus");
            return (Criteria) this;
        }

        public Criteria andDocstatusNotEqualTo(String value) {
            addCriterion("\"DocStatus\" <>", value, "docstatus");
            return (Criteria) this;
        }

        public Criteria andDocstatusGreaterThan(String value) {
            addCriterion("\"DocStatus\" >", value, "docstatus");
            return (Criteria) this;
        }

        public Criteria andDocstatusGreaterThanOrEqualTo(String value) {
            addCriterion("\"DocStatus\" >=", value, "docstatus");
            return (Criteria) this;
        }

        public Criteria andDocstatusLessThan(String value) {
            addCriterion("\"DocStatus\" <", value, "docstatus");
            return (Criteria) this;
        }

        public Criteria andDocstatusLessThanOrEqualTo(String value) {
            addCriterion("\"DocStatus\" <=", value, "docstatus");
            return (Criteria) this;
        }

        public Criteria andDocstatusLike(String value) {
            addCriterion("\"DocStatus\" like", value, "docstatus");
            return (Criteria) this;
        }

        public Criteria andDocstatusNotLike(String value) {
            addCriterion("\"DocStatus\" not like", value, "docstatus");
            return (Criteria) this;
        }

        public Criteria andDocstatusIn(List<String> values) {
            addCriterion("\"DocStatus\" in", values, "docstatus");
            return (Criteria) this;
        }

        public Criteria andDocstatusNotIn(List<String> values) {
            addCriterion("\"DocStatus\" not in", values, "docstatus");
            return (Criteria) this;
        }

        public Criteria andDocstatusBetween(String value1, String value2) {
            addCriterion("\"DocStatus\" between", value1, value2, "docstatus");
            return (Criteria) this;
        }

        public Criteria andDocstatusNotBetween(String value1, String value2) {
            addCriterion("\"DocStatus\" not between", value1, value2, "docstatus");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("\"Creator\" is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("\"Creator\" is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("\"Creator\" =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("\"Creator\" <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("\"Creator\" >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("\"Creator\" >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("\"Creator\" <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("\"Creator\" <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("\"Creator\" like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("\"Creator\" not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("\"Creator\" in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("\"Creator\" not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("\"Creator\" between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("\"Creator\" not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("\"CreateTime\" is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("\"CreateTime\" is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(String value) {
            addCriterion("\"CreateTime\" =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(String value) {
            addCriterion("\"CreateTime\" <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(String value) {
            addCriterion("\"CreateTime\" >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("\"CreateTime\" >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(String value) {
            addCriterion("\"CreateTime\" <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(String value) {
            addCriterion("\"CreateTime\" <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLike(String value) {
            addCriterion("\"CreateTime\" like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotLike(String value) {
            addCriterion("\"CreateTime\" not like", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<String> values) {
            addCriterion("\"CreateTime\" in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<String> values) {
            addCriterion("\"CreateTime\" not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(String value1, String value2) {
            addCriterion("\"CreateTime\" between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(String value1, String value2) {
            addCriterion("\"CreateTime\" not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatorIsNull() {
            addCriterion("\"Updator\" is null");
            return (Criteria) this;
        }

        public Criteria andUpdatorIsNotNull() {
            addCriterion("\"Updator\" is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatorEqualTo(String value) {
            addCriterion("\"Updator\" =", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotEqualTo(String value) {
            addCriterion("\"Updator\" <>", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorGreaterThan(String value) {
            addCriterion("\"Updator\" >", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorGreaterThanOrEqualTo(String value) {
            addCriterion("\"Updator\" >=", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLessThan(String value) {
            addCriterion("\"Updator\" <", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLessThanOrEqualTo(String value) {
            addCriterion("\"Updator\" <=", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLike(String value) {
            addCriterion("\"Updator\" like", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotLike(String value) {
            addCriterion("\"Updator\" not like", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorIn(List<String> values) {
            addCriterion("\"Updator\" in", values, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotIn(List<String> values) {
            addCriterion("\"Updator\" not in", values, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorBetween(String value1, String value2) {
            addCriterion("\"Updator\" between", value1, value2, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotBetween(String value1, String value2) {
            addCriterion("\"Updator\" not between", value1, value2, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("\"UpdateTime\" is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("\"UpdateTime\" is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(String value) {
            addCriterion("\"UpdateTime\" =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(String value) {
            addCriterion("\"UpdateTime\" <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(String value) {
            addCriterion("\"UpdateTime\" >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("\"UpdateTime\" >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(String value) {
            addCriterion("\"UpdateTime\" <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(String value) {
            addCriterion("\"UpdateTime\" <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLike(String value) {
            addCriterion("\"UpdateTime\" like", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotLike(String value) {
            addCriterion("\"UpdateTime\" not like", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<String> values) {
            addCriterion("\"UpdateTime\" in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<String> values) {
            addCriterion("\"UpdateTime\" not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(String value1, String value2) {
            addCriterion("\"UpdateTime\" between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(String value1, String value2) {
            addCriterion("\"UpdateTime\" not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("\"Remark\" is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("\"Remark\" is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("\"Remark\" =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("\"Remark\" <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("\"Remark\" >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("\"Remark\" >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("\"Remark\" <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("\"Remark\" <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("\"Remark\" like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("\"Remark\" not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("\"Remark\" in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("\"Remark\" not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("\"Remark\" between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("\"Remark\" not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MTC_SD_OBJD
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 06 16:47:32 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MTC_SD_OBJD
     *
     * @mbg.generated Wed Mar 06 16:47:32 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}