package io.mtc.modules.sap.entity;

import io.mtc.common.utils.DateUtils;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SaleInvoiceEntity implements Serializable {
    /**
     * 表 : MTC_VIEW_SaleInvoice
     * 对应字段 : DocEntry
     */
    private Integer docentry;

    /**
     * 表 : MTC_VIEW_SaleInvoice
     * 对应字段 : DocNum
     */
    private Integer docnum;

    /**
     * 表 : MTC_VIEW_SaleInvoice
     * 对应字段 : TaxDate
     */
    private Date taxdate;

    /**
     * 表 : MTC_VIEW_SaleInvoice
     * 对应字段 : CardCode
     */
    private String cardcode;

    /**
     * 表 : MTC_VIEW_SaleInvoice
     * 对应字段 : CardName
     */
    private String cardname;

    /**
     * 表 : MTC_VIEW_SaleInvoice
     * 对应字段 : CntctCode
     */
    private Integer cntctcode;

    /**
     * 表 : MTC_VIEW_SaleInvoice
     * 对应字段 : CntctName
     */
    private String cntctname;

    /**
     * 表 : MTC_VIEW_SaleInvoice
     * 对应字段 : TakeGoodsNo
     */
    private String takegoodsno;

    /**
     * 表 : MTC_VIEW_SaleInvoice
     * 对应字段 : takeno
     */
    private String takeno;

    /**
     * 表 : MTC_VIEW_SaleInvoice
     * 对应字段 : WeighNo
     */
    private String weighno;

    /**
     * 表 : MTC_VIEW_SaleInvoice
     * 对应字段 : CarNo
     */
    private String carno;

    /**
     * 表 : MTC_VIEW_SaleInvoice
     * 对应字段 : TotalAmt
     */
    private BigDecimal totalamt;

    /**
     * 表 : MTC_VIEW_SaleInvoice
     * 对应字段 : ArrearsAmt
     */
    private BigDecimal arrearsamt;

    /**
     * 表 : MTC_VIEW_SaleInvoice
     * 对应字段 : InlineNo
     */
    private String inlineno;

    /**
     * 表 : MTC_VIEW_SaleInvoice
     * 对应字段 : DocStatus
     */
    private String docstatus;

    /**
     * 表 : MTC_VIEW_SaleInvoice
     * 对应字段 : DocStatsName
     */
    private String docstatsname;

    /**
     * 表 : MTC_VIEW_SaleInvoice
     * 对应字段 : UserName
     */
    private String username;

    /**
     * 销售分支
     */
    private Integer bplid;

    /**
     * 提货分支
     */
    private Integer takeBplid;

    /**
     * 订料单号
     */
    private String desOrderNum;
    /**
     * 保价单号
     */
    private String priceOrderNum;
    /**
     * 运输方式
     */
    private String tranType;
    /**
     * 业务类型
     */
    private String busiType;

    private String driver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MTC_VIEW_SaleInvoice
     *
     * @mbg.generated Mon Sep 10 15:00:28 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method
     *
     * @return MTC_VIEW_SaleInvoice.DocEntry：null
     */
    public Integer getDocentry() {
        return docentry;
    }

    /**
     * set method
     *
     * @param docentry null
     */
    public void setDocentry(Integer docentry) {
        this.docentry = docentry;
    }

    /**
     * get method
     *
     * @return MTC_VIEW_SaleInvoice.DocNum：null
     */
    public Integer getDocnum() {
        return docnum;
    }

    /**
     * set method
     *
     * @param docnum null
     */
    public void setDocnum(Integer docnum) {
        this.docnum = docnum;
    }

    /**
     * get method
     *
     * @return MTC_VIEW_SaleInvoice.TaxDate：null
     */
    public Date getTaxdate() {
        return taxdate;
    }

    /**
     * set method
     *
     * @param taxdate null
     */
    public void setTaxdate(Date taxdate) {
        this.taxdate = taxdate;
    }

    public String getTaxdateStr() {
        if (taxdate != null) {
            return DateUtils.format(taxdate);
        }
        return null;
    }

    /**
     * get method
     *
     * @return MTC_VIEW_SaleInvoice.CardCode：null
     */
    public String getCardcode() {
        return cardcode;
    }

    /**
     * set method
     *
     * @param cardcode null
     */
    public void setCardcode(String cardcode) {
        this.cardcode = cardcode == null ? null : cardcode.trim();
    }

    /**
     * get method
     *
     * @return MTC_VIEW_SaleInvoice.CardName：null
     */
    public String getCardname() {
        return cardname;
    }

    /**
     * set method
     *
     * @param cardname null
     */
    public void setCardname(String cardname) {
        this.cardname = cardname == null ? null : cardname.trim();
    }

    /**
     * get method
     *
     * @return MTC_VIEW_SaleInvoice.CntctCode：null
     */
    public Integer getCntctcode() {
        return cntctcode;
    }

    /**
     * set method
     *
     * @param cntctcode null
     */
    public void setCntctcode(Integer cntctcode) {
        this.cntctcode = cntctcode;
    }

    /**
     * get method
     *
     * @return MTC_VIEW_SaleInvoice.CntctName：null
     */
    public String getCntctname() {
        return cntctname;
    }

    /**
     * set method
     *
     * @param cntctname null
     */
    public void setCntctname(String cntctname) {
        this.cntctname = cntctname == null ? null : cntctname.trim();
    }

    /**
     * get method
     *
     * @return MTC_VIEW_SaleInvoice.TakeGoodsNo：null
     */
    public String getTakegoodsno() {
        return takegoodsno;
    }

    /**
     * set method
     *
     * @param takegoodsno null
     */
    public void setTakegoodsno(String takegoodsno) {
        this.takegoodsno = takegoodsno == null ? null : takegoodsno.trim();
    }

    /**
     * get method
     *
     * @return MTC_VIEW_SaleInvoice.WeighNo：null
     */
    public String getWeighno() {
        return weighno;
    }

    /**
     * set method
     *
     * @param weighno null
     */
    public void setWeighno(String weighno) {
        this.weighno = weighno == null ? null : weighno.trim();
    }

    /**
     * get method
     *
     * @return MTC_VIEW_SaleInvoice.CarNo：null
     */
    public String getCarno() {
        return carno;
    }

    /**
     * set method
     *
     * @param carno null
     */
    public void setCarno(String carno) {
        this.carno = carno == null ? null : carno.trim();
    }

    /**
     * get method
     *
     * @return MTC_VIEW_SaleInvoice.TotalAmt：null
     */
    public BigDecimal getTotalamt() {
        return totalamt;
    }

    /**
     * set method
     *
     * @param totalamt null
     */
    public void setTotalamt(BigDecimal totalamt) {
        this.totalamt = totalamt;
    }

    /**
     * get method
     *
     * @return MTC_VIEW_SaleInvoice.ArrearsAmt：null
     */
    public BigDecimal getArrearsamt() {
        return arrearsamt;
    }

    /**
     * set method
     *
     * @param arrearsamt null
     */
    public void setArrearsamt(BigDecimal arrearsamt) {
        this.arrearsamt = arrearsamt;
    }

    /**
     * get method
     *
     * @return MTC_VIEW_SaleInvoice.InlineNo：null
     */
    public String getInlineno() {
        return inlineno;
    }

    /**
     * set method
     *
     * @param inlineno null
     */
    public void setInlineno(String inlineno) {
        this.inlineno = inlineno == null ? null : inlineno.trim();
    }

    /**
     * get method
     *
     * @return MTC_VIEW_SaleInvoice.DocStatus：null
     */
    public String getDocstatus() {
        return docstatus;
    }

    /**
     * set method
     *
     * @param docstatus null
     */
    public void setDocstatus(String docstatus) {
        this.docstatus = docstatus == null ? null : docstatus.trim();
    }

    /**
     * get method
     *
     * @return MTC_VIEW_SaleInvoice.DocStatsName：null
     */
    public String getDocstatsname() {
        return docstatsname;
    }

    /**
     * set method
     *
     * @param docstatsname null
     */
    public void setDocstatsname(String docstatsname) {
        this.docstatsname = docstatsname == null ? null : docstatsname.trim();
    }

    /**
     * get method
     *
     * @return MTC_VIEW_SaleInvoice.UserName：null
     */
    public String getUsername() {
        return username;
    }

    /**
     * set method
     *
     * @param username null
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    public Integer getBplid() {
        return bplid;
    }

    public void setBplid(Integer bplid) {
        this.bplid = bplid;
    }

    public Integer getTakeBplid() {
        return takeBplid;
    }

    public void setTakeBplid(Integer takeBplid) {
        this.takeBplid = takeBplid;
    }

    public String getDesOrderNum() {
        return desOrderNum;
    }

    public void setDesOrderNum(String desOrderNum) {
        this.desOrderNum = desOrderNum;
    }

    public String getPriceOrderNum() {
        return priceOrderNum;
    }

    public void setPriceOrderNum(String priceOrderNum) {
        this.priceOrderNum = priceOrderNum;
    }

    public String getTranType() {
        return tranType;
    }

    public void setTranType(String tranType) {
        this.tranType = tranType;
    }

    public String getBusiType() {
        return busiType;
    }

    public void setBusiType(String busiType) {
        this.busiType = busiType;
    }

    public String getTakeno() {
        return takeno;
    }

    public void setTakeno(String takeno) {
        this.takeno = takeno;
    }

    public String getDriver() {
        return driver;
    }

    public void setDriver(String driver) {
        this.driver = driver;
    }
}