package io.mtc.modules.sys.entity;

import com.baomidou.mybatisplus.annotations.KeySequence;
import com.baomidou.mybatisplus.annotations.TableId;
import com.baomidou.mybatisplus.annotations.TableName;
import com.baomidou.mybatisplus.enums.IdType;

import java.io.Serializable;

@TableName("MTC_PRINT_LOG")
@KeySequence("MTC_PRINT_LOG_SEQ")
public class SysPrintLogEntity {
    /**
     * 序列号
     * 表 : MTC_PRINT_LOG
     * 对应字段 : ID
     */
    @TableId(type = IdType.INPUT)
    private Long id;

    /**
     * 用户ID
     * 表 : MTC_PRINT_LOG
     * 对应字段 : USER_ID
     */
    private String userId;

    /**
     * 用户名
     * 表 : MTC_PRINT_LOG
     * 对应字段 : USER_NAME
     */
    private String userName;

    /**
     * 打印日期
     * 表 : MTC_PRINT_LOG
     * 对应字段 : PRINT_DATE
     */
    private String printDate;

    /**
     * 打印时间
     * 表 : MTC_PRINT_LOG
     * 对应字段 : PRINT_TIME
     */
    private String printTime;

    /**
     * 单据类型
     * 表 : MTC_PRINT_LOG
     * 对应字段 : DOCTYPE
     */
    private String doctype;

    /**
     * DocEntry
     * 表 : MTC_PRINT_LOG
     * 对应字段 : DOCENTRY
     */
    private Integer docentry;

    /**
     * 打印模板
     * 表 : MTC_PRINT_LOG
     * 对应字段 : PRINT_TYPE
     */
    private String printType;

    /**
     * 备注
     * 表 : MTC_PRINT_LOG
     * 对应字段 : COMMENT
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MTC_PRINT_LOG
     *
     * @mbg.generated Mon Dec 24 14:27:44 CST 2018
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * get method
     *
     * @return MTC_PRINT_LOG.USER_ID：用户ID
     */
    public String getUserId() {
        return userId;
    }

    /**
     * set method
     *
     * @param userId  用户ID
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * get method
     *
     * @return MTC_PRINT_LOG.USER_NAME：用户名
     */
    public String getUserName() {
        return userName;
    }

    /**
     * set method
     *
     * @param userName  用户名
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * get method
     *
     * @return MTC_PRINT_LOG.PRINT_DATE：打印日期
     */
    public String getPrintDate() {
        return printDate;
    }

    /**
     * set method
     *
     * @param printDate  打印日期
     */
    public void setPrintDate(String printDate) {
        this.printDate = printDate == null ? null : printDate.trim();
    }

    /**
     * get method
     *
     * @return MTC_PRINT_LOG.PRINT_TIME：打印时间
     */
    public String getPrintTime() {
        return printTime;
    }

    /**
     * set method
     *
     * @param printTime  打印时间
     */
    public void setPrintTime(String printTime) {
        this.printTime = printTime == null ? null : printTime.trim();
    }

    /**
     * get method
     *
     * @return MTC_PRINT_LOG.DOCTYPE：单据类型
     */
    public String getDoctype() {
        return doctype;
    }

    /**
     * set method
     *
     * @param doctype  单据类型
     */
    public void setDoctype(String doctype) {
        this.doctype = doctype == null ? null : doctype.trim();
    }

    /**
     * get method
     *
     * @return MTC_PRINT_LOG.DOCENTRY：DocEntry
     */
    public Integer getDocentry() {
        return docentry;
    }

    /**
     * set method
     *
     * @param docentry  DocEntry
     */
    public void setDocentry(Integer docentry) {
        this.docentry = docentry;
    }

    /**
     * get method
     *
     * @return MTC_PRINT_LOG.PRINT_TYPE：打印模板
     */
    public String getPrintType() {
        return printType;
    }

    /**
     * set method
     *
     * @param printType  打印模板
     */
    public void setPrintType(String printType) {
        this.printType = printType == null ? null : printType.trim();
    }

    /**
     * get method
     *
     * @return MTC_PRINT_LOG.COMMENT：备注
     */
    public String getComment() {
        return comment;
    }

    /**
     * set method
     *
     * @param comment  备注
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}