package io.mtc.modules.sys.entity;

import com.baomidou.mybatisplus.annotations.KeySequence;
import com.baomidou.mybatisplus.annotations.TableId;
import com.baomidou.mybatisplus.annotations.TableName;
import com.baomidou.mybatisplus.enums.IdType;
import lombok.Data;

@Data
@TableName("MTC_PRINT_LOG")
@KeySequence("MTC_PRINT_LOG_SEQ")
public class SysPrintLogEntity {
    /**
     * 序列号
     * 表 : MTC_PRINT_LOG
     * 对应字段 : ID
     */
    @TableId(type = IdType.INPUT)
    private Long id;

    /**
     * 用户ID
     * 表 : MTC_PRINT_LOG
     * 对应字段 : USER_ID
     */
    private String userId;

    /**
     * 用户名
     * 表 : MTC_PRINT_LOG
     * 对应字段 : USER_NAME
     */
    private String userName;

    /**
     * 打印日期
     * 表 : MTC_PRINT_LOG
     * 对应字段 : PRINT_DATE
     */
    private String printDate;

    /**
     * 打印时间
     * 表 : MTC_PRINT_LOG
     * 对应字段 : PRINT_TIME
     */
    private String printTime;

    /**
     * 单据类型
     * 表 : MTC_PRINT_LOG
     * 对应字段 : DOCTYPE
     */
    private String doctype;

    /**
     * DocEntry
     * 表 : MTC_PRINT_LOG
     * 对应字段 : DOCENTRY
     */
    private Integer docentry;

    /**
     * 打印模板
     * 表 : MTC_PRINT_LOG
     * 对应字段 : PRINT_TYPE
     */
    private String printType;

    /**
     * 备注
     * 表 : MTC_PRINT_LOG
     * 对应字段 : COMMENT
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MTC_PRINT_LOG
     *
     * @mbg.generated Mon Dec 24 14:27:44 CST 2018
     */
    private static final long serialVersionUID = 1L;
}