package io.mtc.modules.app.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserEntityExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    /**
     *
     */
    public UserEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * @param orderByClause
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * @param distinct
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * @param criteria
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     *
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table @MTC_WUSR
     *
     * @mbg.generated Thu May 09 17:29:05 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCodeIsNull() {
            addCriterion("\"Code\" is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("\"Code\" is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("\"Code\" =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("\"Code\" <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("\"Code\" >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("\"Code\" >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("\"Code\" <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("\"Code\" <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("\"Code\" like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("\"Code\" not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("\"Code\" in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("\"Code\" not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("\"Code\" between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("\"Code\" not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("\"Name\" is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("\"Name\" is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("\"Name\" =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("\"Name\" <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("\"Name\" >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("\"Name\" >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("\"Name\" <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("\"Name\" <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("\"Name\" like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("\"Name\" not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("\"Name\" in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("\"Name\" not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("\"Name\" between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("\"Name\" not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDocentryIsNull() {
            addCriterion("\"DocEntry\" is null");
            return (Criteria) this;
        }

        public Criteria andDocentryIsNotNull() {
            addCriterion("\"DocEntry\" is not null");
            return (Criteria) this;
        }

        public Criteria andDocentryEqualTo(Integer value) {
            addCriterion("\"DocEntry\" =", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryNotEqualTo(Integer value) {
            addCriterion("\"DocEntry\" <>", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryGreaterThan(Integer value) {
            addCriterion("\"DocEntry\" >", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"DocEntry\" >=", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryLessThan(Integer value) {
            addCriterion("\"DocEntry\" <", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryLessThanOrEqualTo(Integer value) {
            addCriterion("\"DocEntry\" <=", value, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryIn(List<Integer> values) {
            addCriterion("\"DocEntry\" in", values, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryNotIn(List<Integer> values) {
            addCriterion("\"DocEntry\" not in", values, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryBetween(Integer value1, Integer value2) {
            addCriterion("\"DocEntry\" between", value1, value2, "docentry");
            return (Criteria) this;
        }

        public Criteria andDocentryNotBetween(Integer value1, Integer value2) {
            addCriterion("\"DocEntry\" not between", value1, value2, "docentry");
            return (Criteria) this;
        }

        public Criteria andCanceledIsNull() {
            addCriterion("\"Canceled\" is null");
            return (Criteria) this;
        }

        public Criteria andCanceledIsNotNull() {
            addCriterion("\"Canceled\" is not null");
            return (Criteria) this;
        }

        public Criteria andCanceledEqualTo(String value) {
            addCriterion("\"Canceled\" =", value, "canceled");
            return (Criteria) this;
        }

        public Criteria andCanceledNotEqualTo(String value) {
            addCriterion("\"Canceled\" <>", value, "canceled");
            return (Criteria) this;
        }

        public Criteria andCanceledGreaterThan(String value) {
            addCriterion("\"Canceled\" >", value, "canceled");
            return (Criteria) this;
        }

        public Criteria andCanceledGreaterThanOrEqualTo(String value) {
            addCriterion("\"Canceled\" >=", value, "canceled");
            return (Criteria) this;
        }

        public Criteria andCanceledLessThan(String value) {
            addCriterion("\"Canceled\" <", value, "canceled");
            return (Criteria) this;
        }

        public Criteria andCanceledLessThanOrEqualTo(String value) {
            addCriterion("\"Canceled\" <=", value, "canceled");
            return (Criteria) this;
        }

        public Criteria andCanceledLike(String value) {
            addCriterion("\"Canceled\" like", value, "canceled");
            return (Criteria) this;
        }

        public Criteria andCanceledNotLike(String value) {
            addCriterion("\"Canceled\" not like", value, "canceled");
            return (Criteria) this;
        }

        public Criteria andCanceledIn(List<String> values) {
            addCriterion("\"Canceled\" in", values, "canceled");
            return (Criteria) this;
        }

        public Criteria andCanceledNotIn(List<String> values) {
            addCriterion("\"Canceled\" not in", values, "canceled");
            return (Criteria) this;
        }

        public Criteria andCanceledBetween(String value1, String value2) {
            addCriterion("\"Canceled\" between", value1, value2, "canceled");
            return (Criteria) this;
        }

        public Criteria andCanceledNotBetween(String value1, String value2) {
            addCriterion("\"Canceled\" not between", value1, value2, "canceled");
            return (Criteria) this;
        }

        public Criteria andObjectIsNull() {
            addCriterion("\"Object\" is null");
            return (Criteria) this;
        }

        public Criteria andObjectIsNotNull() {
            addCriterion("\"Object\" is not null");
            return (Criteria) this;
        }

        public Criteria andObjectEqualTo(String value) {
            addCriterion("\"Object\" =", value, "object");
            return (Criteria) this;
        }

        public Criteria andObjectNotEqualTo(String value) {
            addCriterion("\"Object\" <>", value, "object");
            return (Criteria) this;
        }

        public Criteria andObjectGreaterThan(String value) {
            addCriterion("\"Object\" >", value, "object");
            return (Criteria) this;
        }

        public Criteria andObjectGreaterThanOrEqualTo(String value) {
            addCriterion("\"Object\" >=", value, "object");
            return (Criteria) this;
        }

        public Criteria andObjectLessThan(String value) {
            addCriterion("\"Object\" <", value, "object");
            return (Criteria) this;
        }

        public Criteria andObjectLessThanOrEqualTo(String value) {
            addCriterion("\"Object\" <=", value, "object");
            return (Criteria) this;
        }

        public Criteria andObjectLike(String value) {
            addCriterion("\"Object\" like", value, "object");
            return (Criteria) this;
        }

        public Criteria andObjectNotLike(String value) {
            addCriterion("\"Object\" not like", value, "object");
            return (Criteria) this;
        }

        public Criteria andObjectIn(List<String> values) {
            addCriterion("\"Object\" in", values, "object");
            return (Criteria) this;
        }

        public Criteria andObjectNotIn(List<String> values) {
            addCriterion("\"Object\" not in", values, "object");
            return (Criteria) this;
        }

        public Criteria andObjectBetween(String value1, String value2) {
            addCriterion("\"Object\" between", value1, value2, "object");
            return (Criteria) this;
        }

        public Criteria andObjectNotBetween(String value1, String value2) {
            addCriterion("\"Object\" not between", value1, value2, "object");
            return (Criteria) this;
        }

        public Criteria andLoginstIsNull() {
            addCriterion("\"LogInst\" is null");
            return (Criteria) this;
        }

        public Criteria andLoginstIsNotNull() {
            addCriterion("\"LogInst\" is not null");
            return (Criteria) this;
        }

        public Criteria andLoginstEqualTo(Integer value) {
            addCriterion("\"LogInst\" =", value, "loginst");
            return (Criteria) this;
        }

        public Criteria andLoginstNotEqualTo(Integer value) {
            addCriterion("\"LogInst\" <>", value, "loginst");
            return (Criteria) this;
        }

        public Criteria andLoginstGreaterThan(Integer value) {
            addCriterion("\"LogInst\" >", value, "loginst");
            return (Criteria) this;
        }

        public Criteria andLoginstGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"LogInst\" >=", value, "loginst");
            return (Criteria) this;
        }

        public Criteria andLoginstLessThan(Integer value) {
            addCriterion("\"LogInst\" <", value, "loginst");
            return (Criteria) this;
        }

        public Criteria andLoginstLessThanOrEqualTo(Integer value) {
            addCriterion("\"LogInst\" <=", value, "loginst");
            return (Criteria) this;
        }

        public Criteria andLoginstIn(List<Integer> values) {
            addCriterion("\"LogInst\" in", values, "loginst");
            return (Criteria) this;
        }

        public Criteria andLoginstNotIn(List<Integer> values) {
            addCriterion("\"LogInst\" not in", values, "loginst");
            return (Criteria) this;
        }

        public Criteria andLoginstBetween(Integer value1, Integer value2) {
            addCriterion("\"LogInst\" between", value1, value2, "loginst");
            return (Criteria) this;
        }

        public Criteria andLoginstNotBetween(Integer value1, Integer value2) {
            addCriterion("\"LogInst\" not between", value1, value2, "loginst");
            return (Criteria) this;
        }

        public Criteria andUsersignIsNull() {
            addCriterion("\"UserSign\" is null");
            return (Criteria) this;
        }

        public Criteria andUsersignIsNotNull() {
            addCriterion("\"UserSign\" is not null");
            return (Criteria) this;
        }

        public Criteria andUsersignEqualTo(Integer value) {
            addCriterion("\"UserSign\" =", value, "usersign");
            return (Criteria) this;
        }

        public Criteria andUsersignNotEqualTo(Integer value) {
            addCriterion("\"UserSign\" <>", value, "usersign");
            return (Criteria) this;
        }

        public Criteria andUsersignGreaterThan(Integer value) {
            addCriterion("\"UserSign\" >", value, "usersign");
            return (Criteria) this;
        }

        public Criteria andUsersignGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"UserSign\" >=", value, "usersign");
            return (Criteria) this;
        }

        public Criteria andUsersignLessThan(Integer value) {
            addCriterion("\"UserSign\" <", value, "usersign");
            return (Criteria) this;
        }

        public Criteria andUsersignLessThanOrEqualTo(Integer value) {
            addCriterion("\"UserSign\" <=", value, "usersign");
            return (Criteria) this;
        }

        public Criteria andUsersignIn(List<Integer> values) {
            addCriterion("\"UserSign\" in", values, "usersign");
            return (Criteria) this;
        }

        public Criteria andUsersignNotIn(List<Integer> values) {
            addCriterion("\"UserSign\" not in", values, "usersign");
            return (Criteria) this;
        }

        public Criteria andUsersignBetween(Integer value1, Integer value2) {
            addCriterion("\"UserSign\" between", value1, value2, "usersign");
            return (Criteria) this;
        }

        public Criteria andUsersignNotBetween(Integer value1, Integer value2) {
            addCriterion("\"UserSign\" not between", value1, value2, "usersign");
            return (Criteria) this;
        }

        public Criteria andTransferedIsNull() {
            addCriterion("\"Transfered\" is null");
            return (Criteria) this;
        }

        public Criteria andTransferedIsNotNull() {
            addCriterion("\"Transfered\" is not null");
            return (Criteria) this;
        }

        public Criteria andTransferedEqualTo(String value) {
            addCriterion("\"Transfered\" =", value, "transfered");
            return (Criteria) this;
        }

        public Criteria andTransferedNotEqualTo(String value) {
            addCriterion("\"Transfered\" <>", value, "transfered");
            return (Criteria) this;
        }

        public Criteria andTransferedGreaterThan(String value) {
            addCriterion("\"Transfered\" >", value, "transfered");
            return (Criteria) this;
        }

        public Criteria andTransferedGreaterThanOrEqualTo(String value) {
            addCriterion("\"Transfered\" >=", value, "transfered");
            return (Criteria) this;
        }

        public Criteria andTransferedLessThan(String value) {
            addCriterion("\"Transfered\" <", value, "transfered");
            return (Criteria) this;
        }

        public Criteria andTransferedLessThanOrEqualTo(String value) {
            addCriterion("\"Transfered\" <=", value, "transfered");
            return (Criteria) this;
        }

        public Criteria andTransferedLike(String value) {
            addCriterion("\"Transfered\" like", value, "transfered");
            return (Criteria) this;
        }

        public Criteria andTransferedNotLike(String value) {
            addCriterion("\"Transfered\" not like", value, "transfered");
            return (Criteria) this;
        }

        public Criteria andTransferedIn(List<String> values) {
            addCriterion("\"Transfered\" in", values, "transfered");
            return (Criteria) this;
        }

        public Criteria andTransferedNotIn(List<String> values) {
            addCriterion("\"Transfered\" not in", values, "transfered");
            return (Criteria) this;
        }

        public Criteria andTransferedBetween(String value1, String value2) {
            addCriterion("\"Transfered\" between", value1, value2, "transfered");
            return (Criteria) this;
        }

        public Criteria andTransferedNotBetween(String value1, String value2) {
            addCriterion("\"Transfered\" not between", value1, value2, "transfered");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("\"CreateDate\" is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("\"CreateDate\" is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("\"CreateDate\" =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("\"CreateDate\" <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("\"CreateDate\" >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("\"CreateDate\" >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("\"CreateDate\" <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("\"CreateDate\" <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("\"CreateDate\" in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("\"CreateDate\" not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("\"CreateDate\" between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("\"CreateDate\" not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("\"CreateTime\" is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("\"CreateTime\" is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Short value) {
            addCriterion("\"CreateTime\" =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Short value) {
            addCriterion("\"CreateTime\" <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Short value) {
            addCriterion("\"CreateTime\" >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Short value) {
            addCriterion("\"CreateTime\" >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Short value) {
            addCriterion("\"CreateTime\" <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Short value) {
            addCriterion("\"CreateTime\" <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Short> values) {
            addCriterion("\"CreateTime\" in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Short> values) {
            addCriterion("\"CreateTime\" not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Short value1, Short value2) {
            addCriterion("\"CreateTime\" between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Short value1, Short value2) {
            addCriterion("\"CreateTime\" not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNull() {
            addCriterion("\"UpdateDate\" is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIsNotNull() {
            addCriterion("\"UpdateDate\" is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedateEqualTo(Date value) {
            addCriterion("\"UpdateDate\" =", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotEqualTo(Date value) {
            addCriterion("\"UpdateDate\" <>", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThan(Date value) {
            addCriterion("\"UpdateDate\" >", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("\"UpdateDate\" >=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThan(Date value) {
            addCriterion("\"UpdateDate\" <", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateLessThanOrEqualTo(Date value) {
            addCriterion("\"UpdateDate\" <=", value, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateIn(List<Date> values) {
            addCriterion("\"UpdateDate\" in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotIn(List<Date> values) {
            addCriterion("\"UpdateDate\" not in", values, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateBetween(Date value1, Date value2) {
            addCriterion("\"UpdateDate\" between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatedateNotBetween(Date value1, Date value2) {
            addCriterion("\"UpdateDate\" not between", value1, value2, "updatedate");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("\"UpdateTime\" is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("\"UpdateTime\" is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Short value) {
            addCriterion("\"UpdateTime\" =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Short value) {
            addCriterion("\"UpdateTime\" <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Short value) {
            addCriterion("\"UpdateTime\" >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Short value) {
            addCriterion("\"UpdateTime\" >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Short value) {
            addCriterion("\"UpdateTime\" <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Short value) {
            addCriterion("\"UpdateTime\" <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Short> values) {
            addCriterion("\"UpdateTime\" in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Short> values) {
            addCriterion("\"UpdateTime\" not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Short value1, Short value2) {
            addCriterion("\"UpdateTime\" between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Short value1, Short value2) {
            addCriterion("\"UpdateTime\" not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andDatasourceIsNull() {
            addCriterion("\"DataSource\" is null");
            return (Criteria) this;
        }

        public Criteria andDatasourceIsNotNull() {
            addCriterion("\"DataSource\" is not null");
            return (Criteria) this;
        }

        public Criteria andDatasourceEqualTo(String value) {
            addCriterion("\"DataSource\" =", value, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceNotEqualTo(String value) {
            addCriterion("\"DataSource\" <>", value, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceGreaterThan(String value) {
            addCriterion("\"DataSource\" >", value, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceGreaterThanOrEqualTo(String value) {
            addCriterion("\"DataSource\" >=", value, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceLessThan(String value) {
            addCriterion("\"DataSource\" <", value, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceLessThanOrEqualTo(String value) {
            addCriterion("\"DataSource\" <=", value, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceLike(String value) {
            addCriterion("\"DataSource\" like", value, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceNotLike(String value) {
            addCriterion("\"DataSource\" not like", value, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceIn(List<String> values) {
            addCriterion("\"DataSource\" in", values, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceNotIn(List<String> values) {
            addCriterion("\"DataSource\" not in", values, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceBetween(String value1, String value2) {
            addCriterion("\"DataSource\" between", value1, value2, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceNotBetween(String value1, String value2) {
            addCriterion("\"DataSource\" not between", value1, value2, "datasource");
            return (Criteria) this;
        }

        public Criteria andUPasswordIsNull() {
            addCriterion("\"U_PassWord\" is null");
            return (Criteria) this;
        }

        public Criteria andUPasswordIsNotNull() {
            addCriterion("\"U_PassWord\" is not null");
            return (Criteria) this;
        }

        public Criteria andUPasswordEqualTo(String value) {
            addCriterion("\"U_PassWord\" =", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordNotEqualTo(String value) {
            addCriterion("\"U_PassWord\" <>", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordGreaterThan(String value) {
            addCriterion("\"U_PassWord\" >", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("\"U_PassWord\" >=", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordLessThan(String value) {
            addCriterion("\"U_PassWord\" <", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordLessThanOrEqualTo(String value) {
            addCriterion("\"U_PassWord\" <=", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordLike(String value) {
            addCriterion("\"U_PassWord\" like", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordNotLike(String value) {
            addCriterion("\"U_PassWord\" not like", value, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordIn(List<String> values) {
            addCriterion("\"U_PassWord\" in", values, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordNotIn(List<String> values) {
            addCriterion("\"U_PassWord\" not in", values, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordBetween(String value1, String value2) {
            addCriterion("\"U_PassWord\" between", value1, value2, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUPasswordNotBetween(String value1, String value2) {
            addCriterion("\"U_PassWord\" not between", value1, value2, "uPassword");
            return (Criteria) this;
        }

        public Criteria andUOacodeIsNull() {
            addCriterion("\"U_OACode\" is null");
            return (Criteria) this;
        }

        public Criteria andUOacodeIsNotNull() {
            addCriterion("\"U_OACode\" is not null");
            return (Criteria) this;
        }

        public Criteria andUOacodeEqualTo(String value) {
            addCriterion("\"U_OACode\" =", value, "uOacode");
            return (Criteria) this;
        }

        public Criteria andUOacodeNotEqualTo(String value) {
            addCriterion("\"U_OACode\" <>", value, "uOacode");
            return (Criteria) this;
        }

        public Criteria andUOacodeGreaterThan(String value) {
            addCriterion("\"U_OACode\" >", value, "uOacode");
            return (Criteria) this;
        }

        public Criteria andUOacodeGreaterThanOrEqualTo(String value) {
            addCriterion("\"U_OACode\" >=", value, "uOacode");
            return (Criteria) this;
        }

        public Criteria andUOacodeLessThan(String value) {
            addCriterion("\"U_OACode\" <", value, "uOacode");
            return (Criteria) this;
        }

        public Criteria andUOacodeLessThanOrEqualTo(String value) {
            addCriterion("\"U_OACode\" <=", value, "uOacode");
            return (Criteria) this;
        }

        public Criteria andUOacodeLike(String value) {
            addCriterion("\"U_OACode\" like", value, "uOacode");
            return (Criteria) this;
        }

        public Criteria andUOacodeNotLike(String value) {
            addCriterion("\"U_OACode\" not like", value, "uOacode");
            return (Criteria) this;
        }

        public Criteria andUOacodeIn(List<String> values) {
            addCriterion("\"U_OACode\" in", values, "uOacode");
            return (Criteria) this;
        }

        public Criteria andUOacodeNotIn(List<String> values) {
            addCriterion("\"U_OACode\" not in", values, "uOacode");
            return (Criteria) this;
        }

        public Criteria andUOacodeBetween(String value1, String value2) {
            addCriterion("\"U_OACode\" between", value1, value2, "uOacode");
            return (Criteria) this;
        }

        public Criteria andUOacodeNotBetween(String value1, String value2) {
            addCriterion("\"U_OACode\" not between", value1, value2, "uOacode");
            return (Criteria) this;
        }

        public Criteria andUSappistnIsNull() {
            addCriterion("\"U_SAPPistn\" is null");
            return (Criteria) this;
        }

        public Criteria andUSappistnIsNotNull() {
            addCriterion("\"U_SAPPistn\" is not null");
            return (Criteria) this;
        }

        public Criteria andUSappistnEqualTo(String value) {
            addCriterion("\"U_SAPPistn\" =", value, "uSappistn");
            return (Criteria) this;
        }

        public Criteria andUSappistnNotEqualTo(String value) {
            addCriterion("\"U_SAPPistn\" <>", value, "uSappistn");
            return (Criteria) this;
        }

        public Criteria andUSappistnGreaterThan(String value) {
            addCriterion("\"U_SAPPistn\" >", value, "uSappistn");
            return (Criteria) this;
        }

        public Criteria andUSappistnGreaterThanOrEqualTo(String value) {
            addCriterion("\"U_SAPPistn\" >=", value, "uSappistn");
            return (Criteria) this;
        }

        public Criteria andUSappistnLessThan(String value) {
            addCriterion("\"U_SAPPistn\" <", value, "uSappistn");
            return (Criteria) this;
        }

        public Criteria andUSappistnLessThanOrEqualTo(String value) {
            addCriterion("\"U_SAPPistn\" <=", value, "uSappistn");
            return (Criteria) this;
        }

        public Criteria andUSappistnLike(String value) {
            addCriterion("\"U_SAPPistn\" like", value, "uSappistn");
            return (Criteria) this;
        }

        public Criteria andUSappistnNotLike(String value) {
            addCriterion("\"U_SAPPistn\" not like", value, "uSappistn");
            return (Criteria) this;
        }

        public Criteria andUSappistnIn(List<String> values) {
            addCriterion("\"U_SAPPistn\" in", values, "uSappistn");
            return (Criteria) this;
        }

        public Criteria andUSappistnNotIn(List<String> values) {
            addCriterion("\"U_SAPPistn\" not in", values, "uSappistn");
            return (Criteria) this;
        }

        public Criteria andUSappistnBetween(String value1, String value2) {
            addCriterion("\"U_SAPPistn\" between", value1, value2, "uSappistn");
            return (Criteria) this;
        }

        public Criteria andUSappistnNotBetween(String value1, String value2) {
            addCriterion("\"U_SAPPistn\" not between", value1, value2, "uSappistn");
            return (Criteria) this;
        }

        public Criteria andUWechatIsNull() {
            addCriterion("\"U_WeChat\" is null");
            return (Criteria) this;
        }

        public Criteria andUWechatIsNotNull() {
            addCriterion("\"U_WeChat\" is not null");
            return (Criteria) this;
        }

        public Criteria andUWechatEqualTo(String value) {
            addCriterion("\"U_WeChat\" =", value, "uWechat");
            return (Criteria) this;
        }

        public Criteria andUWechatNotEqualTo(String value) {
            addCriterion("\"U_WeChat\" <>", value, "uWechat");
            return (Criteria) this;
        }

        public Criteria andUWechatGreaterThan(String value) {
            addCriterion("\"U_WeChat\" >", value, "uWechat");
            return (Criteria) this;
        }

        public Criteria andUWechatGreaterThanOrEqualTo(String value) {
            addCriterion("\"U_WeChat\" >=", value, "uWechat");
            return (Criteria) this;
        }

        public Criteria andUWechatLessThan(String value) {
            addCriterion("\"U_WeChat\" <", value, "uWechat");
            return (Criteria) this;
        }

        public Criteria andUWechatLessThanOrEqualTo(String value) {
            addCriterion("\"U_WeChat\" <=", value, "uWechat");
            return (Criteria) this;
        }

        public Criteria andUWechatLike(String value) {
            addCriterion("\"U_WeChat\" like", value, "uWechat");
            return (Criteria) this;
        }

        public Criteria andUWechatNotLike(String value) {
            addCriterion("\"U_WeChat\" not like", value, "uWechat");
            return (Criteria) this;
        }

        public Criteria andUWechatIn(List<String> values) {
            addCriterion("\"U_WeChat\" in", values, "uWechat");
            return (Criteria) this;
        }

        public Criteria andUWechatNotIn(List<String> values) {
            addCriterion("\"U_WeChat\" not in", values, "uWechat");
            return (Criteria) this;
        }

        public Criteria andUWechatBetween(String value1, String value2) {
            addCriterion("\"U_WeChat\" between", value1, value2, "uWechat");
            return (Criteria) this;
        }

        public Criteria andUWechatNotBetween(String value1, String value2) {
            addCriterion("\"U_WeChat\" not between", value1, value2, "uWechat");
            return (Criteria) this;
        }

        public Criteria andUIsactiveIsNull() {
            addCriterion("\"U_IsActive\" is null");
            return (Criteria) this;
        }

        public Criteria andUIsactiveIsNotNull() {
            addCriterion("\"U_IsActive\" is not null");
            return (Criteria) this;
        }

        public Criteria andUIsactiveEqualTo(String value) {
            addCriterion("\"U_IsActive\" =", value, "uIsactive");
            return (Criteria) this;
        }

        public Criteria andUIsactiveNotEqualTo(String value) {
            addCriterion("\"U_IsActive\" <>", value, "uIsactive");
            return (Criteria) this;
        }

        public Criteria andUIsactiveGreaterThan(String value) {
            addCriterion("\"U_IsActive\" >", value, "uIsactive");
            return (Criteria) this;
        }

        public Criteria andUIsactiveGreaterThanOrEqualTo(String value) {
            addCriterion("\"U_IsActive\" >=", value, "uIsactive");
            return (Criteria) this;
        }

        public Criteria andUIsactiveLessThan(String value) {
            addCriterion("\"U_IsActive\" <", value, "uIsactive");
            return (Criteria) this;
        }

        public Criteria andUIsactiveLessThanOrEqualTo(String value) {
            addCriterion("\"U_IsActive\" <=", value, "uIsactive");
            return (Criteria) this;
        }

        public Criteria andUIsactiveLike(String value) {
            addCriterion("\"U_IsActive\" like", value, "uIsactive");
            return (Criteria) this;
        }

        public Criteria andUIsactiveNotLike(String value) {
            addCriterion("\"U_IsActive\" not like", value, "uIsactive");
            return (Criteria) this;
        }

        public Criteria andUIsactiveIn(List<String> values) {
            addCriterion("\"U_IsActive\" in", values, "uIsactive");
            return (Criteria) this;
        }

        public Criteria andUIsactiveNotIn(List<String> values) {
            addCriterion("\"U_IsActive\" not in", values, "uIsactive");
            return (Criteria) this;
        }

        public Criteria andUIsactiveBetween(String value1, String value2) {
            addCriterion("\"U_IsActive\" between", value1, value2, "uIsactive");
            return (Criteria) this;
        }

        public Criteria andUIsactiveNotBetween(String value1, String value2) {
            addCriterion("\"U_IsActive\" not between", value1, value2, "uIsactive");
            return (Criteria) this;
        }

        public Criteria andUEmpidIsNull() {
            addCriterion("\"U_empId\" is null");
            return (Criteria) this;
        }

        public Criteria andUEmpidIsNotNull() {
            addCriterion("\"U_empId\" is not null");
            return (Criteria) this;
        }

        public Criteria andUEmpidEqualTo(String value) {
            addCriterion("\"U_empId\" =", value, "uEmpid");
            return (Criteria) this;
        }

        public Criteria andUEmpidNotEqualTo(String value) {
            addCriterion("\"U_empId\" <>", value, "uEmpid");
            return (Criteria) this;
        }

        public Criteria andUEmpidGreaterThan(String value) {
            addCriterion("\"U_empId\" >", value, "uEmpid");
            return (Criteria) this;
        }

        public Criteria andUEmpidGreaterThanOrEqualTo(String value) {
            addCriterion("\"U_empId\" >=", value, "uEmpid");
            return (Criteria) this;
        }

        public Criteria andUEmpidLessThan(String value) {
            addCriterion("\"U_empId\" <", value, "uEmpid");
            return (Criteria) this;
        }

        public Criteria andUEmpidLessThanOrEqualTo(String value) {
            addCriterion("\"U_empId\" <=", value, "uEmpid");
            return (Criteria) this;
        }

        public Criteria andUEmpidLike(String value) {
            addCriterion("\"U_empId\" like", value, "uEmpid");
            return (Criteria) this;
        }

        public Criteria andUEmpidNotLike(String value) {
            addCriterion("\"U_empId\" not like", value, "uEmpid");
            return (Criteria) this;
        }

        public Criteria andUEmpidIn(List<String> values) {
            addCriterion("\"U_empId\" in", values, "uEmpid");
            return (Criteria) this;
        }

        public Criteria andUEmpidNotIn(List<String> values) {
            addCriterion("\"U_empId\" not in", values, "uEmpid");
            return (Criteria) this;
        }

        public Criteria andUEmpidBetween(String value1, String value2) {
            addCriterion("\"U_empId\" between", value1, value2, "uEmpid");
            return (Criteria) this;
        }

        public Criteria andUEmpidNotBetween(String value1, String value2) {
            addCriterion("\"U_empId\" not between", value1, value2, "uEmpid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table @MTC_WUSR
     *
     * @mbg.generated do_not_delete_during_merge Thu May 09 17:29:05 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table @MTC_WUSR
     *
     * @mbg.generated Thu May 09 17:29:05 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}